- README
Makes it easier to find them and learn about the upstream status.
> README: clarify status of qemu tpm patches

- src/swtpm/ctrlchannel.c
Enable receiving control commands in small chnunks. Allow 500ms
for the whole control command to be received.
> swtpm: enable receiving control commands in chunks

- src/swtpm/common.c
- src/swtpm/ctrlchannel.c
- src/swtpm/ctrlchannel.h
- src/swtpm/mainloop.c
- src/swtpm/server.c
- src/swtpm/server.h
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm_ioctl/tpm_ioctl.c
- tests/_test_migration_key
- tests/common
- tests/test_ctrlchannel
- tests/test_ctrlchannel2
- tests/test_ctrlchannel4
- tests/test_vtpm_proxy
Improve the tests and reduce the number of failures we get when many tests are running concurrently and we may hit timeouts.
> Improve tests to reduce failures due to timeout and concurrency

- tests/common
> tests: implement missing wait_file_gone function

- src/swtpm/utils.c
- src/swtpm_setup/swtpm_setup.sh.in
> swtpm_setup: Fix a couple of typos

- configure.ac
- src/swtpm/Makefile.am
- src/swtpm/swtpm_aes.c
- src/swtpm/swtpm_aes.h
- src/swtpm/swtpm_nvfile.c
- tests/Makefile.am
This series of patches is a step towards building swtpm on older systems, such as RHEL 6.
> Step towards building swtpm on older systems (RHEL 6)

- tests/_test_hashing2
- tests/_test_migration_key
- tests/_test_save_load_encrypted_state
- tests/_test_setbuffersize
- tests/_test_tpm2_getcap
- tests/_test_tpm2_hashing2
- tests/_test_tpm2_hashing3
- tests/_test_tpm2_migration_key
- tests/_test_tpm2_probe
- tests/_test_tpm2_save_load_encrypted_state
- tests/_test_tpm2_setbuffersize
- tests/_test_tpm2_wrongorder
- tests/_test_tpm_probe
- tests/common
This series of patches removes some output from the test cases but also captures the output and compares it with expected output.
> Make test log less noisy

- configure.ac
- src/swtpm_cert/ek-cert.c
- tests/test_swtpm_cert
- tests/test_tpm2_swtpm_cert
- tests/test_tpm2_swtpm_cert_ecc
This series of patches fixes some memory leaks and linking with unnecessary libraries.
Stefan
> Fix some memory leaks and linking with unnecessary libraries

- .travis.yml
Use Travis for parallel test runs and do address sanitization checks.
Stefan
> Use Travis for parallel test runs and do address sanitization checks

- tests/_test_encrypted_state
- tests/_test_tpm2_encrypted_state
- tests/test_parameters
Fix a test case that had missing filesizes for comparison.
Have the test cases for encrypted keys use binary keys once so we get better code coverage.
Stefan
> Some improvements to test cases

- src/swtpm/ctrlchannel.c
Make sure that the msg parameter passed into recvmsg wasn't modified
by the library and verify that the pointers and sizes it contains are
still valid after the call. This addresses an issue raised by Coverity.
> swtpm: Coverity: Check msg parameter upon return from recvmsg

- .travis.yml
- src/swtpm/ctrlchannel.c
- src/swtpm_bios/tpm_bios.c
Fix issues detected by ubsan and add ubsan test run for Travis.
Stefan
> Fix issues detected by ubsan and add ubsan test run for Travis

- .gitignore
- CHANGES
- configure.ac
- debian/changelog
- debian/control
- debian/rules
- debian/swtpm-tools.postinst.in
- run_tests
- tests/test_tpm2_samples_swtpm_localca_pkcs11
This PR fixes some issues with tests cases and prepares for the 0.1 release.
> Fix some issues with test cases and prepare for 0.1 release

- dist/swtpm.spec
- dist/swtpm.spec.in
- samples/swtpm-localca.in
- src/swtpm_setup/swtpm_setup.sh.in
This PR backports a few fixes from master to stable-0.1.0.
> Backport some fixes to stable-0.1.0

- .gitignore
- .travis.yml
- src/swtpm/utils.c
- tests/common
- tests/test_commandline
- tests/test_ctrlchannel
- tests/test_tpm2_ctrlchannel2
Modify test cases to provide better coverage.
Fix some bugs on the way.
> Modify tests to provide better coverage

- src/swtpm_bios/tpm_bios.c
- src/swtpm_ioctl/tpm_ioctl.c
- tests/test_ctrlchannel2
Convert client tools to use getaddrinfo for hostname resolution so that we also get IPv6 support.
> Support IPv6 in client tools

- .travis.yml
- src/swtpm/options.c
Fix an illegal heap access and use sanitization in libtpms when using it for swtpm.
> Fix an illegal heap access and use sanitization in libtpms when using it for swtpm

- tests/test_tpm2_ibmtss2
> tests: Use tag v1470 for revision of ibmtss2 test suite

- src/swtpm/ctrlchannel.c
- src/swtpm/mainloop.c
- src/swtpm/mainloop.h
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/swtpm_io.c
- src/swtpm/swtpm_io.h
This is a series of cleanups that improve consistency and simplify things.
> Cleanup series

- include/swtpm/tpm_ioctl.h
- man/man8/swtpm.8
- man/man8/swtpm.pod
- man/man8/swtpm_cuse.8
- man/man8/swtpm_cuse.pod
- src/swtpm/ctrlchannel.c
- src/swtpm/cuse_tpm.c
Report binary capability for TPM 2 data channel header
> Report binary capability for TPM 2 data channel header

- src/swtpm/capabilities.c
Signed-off-by: stefan Berger <stefanb@linux.ibm.com>
> swtpm: Address Coverity's dead code complaint

- dist/swtpm.spec
- dist/swtpm.spec.in
> rpm: Adjust the RPM spec for 0.2.0 release

- src/swtpm/swtpm_aes.c
Signed-off-by: Jeremy Liu <liujiong@gohighsec.com>
> swtpm: Correct parameter name typo

- CHANGES
- configure.ac
- debian/changelog
- debian/control
- debian/rules
- dist/swtpm.spec
- dist/swtpm.spec.in
A few patches to prepare for 0.3.0. release.
> Prepare for 0.3.0 release

- .travis.yml
- dist/swtpm.spec
- dist/swtpm.spec.in
Update the gitcommit for an rpm checkout of 0.3.0 code and use VERBOSE=1 when running `make check`.
> Two more few patches for 0.3.0

- debian/changelog
> Debian: Adjust changelog for 0.3.1 release

- dist/swtpm.spec
- dist/swtpm.spec.in
> RPM: Update gitcommit for a useful 0.3.1 checkout

- configure.ac
- debian/changelog
- dist/swtpm.spec
Bump up the version to 0.4.0 for the next development cycle.
> Bump version to 0.4.0 for new dev cycle

- src/swtpm_setup/swtpm_setup.sh.in
Remove some commented code and some code that isn't executed any
differently for the user id that's running it.
> swtpm_setup: Remove some old cruft

- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/tpmlib.c
- tests/test_tpm12
This PR backports a couple of recent patches to the 0.3.0-stable branch.
> Backport a couple of patches to 0.3.0-stable

- CHANGES
- debian/changelog
- dist/swtpm.spec
- dist/swtpm.spec.in
This PR prepares for libtpms 0.1.1 release
> Prepare for swtpm 0.1.1 release

- CHANGES
- debian/changelog
- dist/swtpm.spec
- dist/swtpm.spec.in
This PR prepares for swtpm 0.2.1 release
> Prepare for swtpm 0.2.1 release

- CHANGES
- debian/changelog
- debian/swtpm-cuse.install
- debian/swtpm-tools.postinst.in
- dist/swtpm.spec
- dist/swtpm.spec.in
This PR prepares for swtpm 0.3.2 release
> Prepare for swtpm 0.3.2 release

- CHANGES
- configure.ac
- src/swtpm/Makefile.am
This PR fixes a build issue when using clang (issue #280) and extends the CHANGES document with changes for 0.4.0
> Fix clang build issue and extend CHANGES document for 0.4.0

- tests/test_tpm2_samples_create_tpmca
- tests/test_tpm2_save_load_state
- tests/test_tpm2_setbuffersize
Some test cases were assigned the same ports. This PR resolves these issues.
> tests: Resolve port assignment conflicts

- configure.ac
> build-sys: Have configure display swtpm version being built

- .gitignore
- configure.ac
- samples/Makefile.am
- samples/swtpm-create-user-config-files.in
Implement a script that creates the user config files in the
${XDG_CONFIG_HOME} directory and sub-directories.
> samples: Implement script to create user config files

- man/man8/swtpm-localca.options.pod
- man/man8/swtpm_ioctl.pod
Fix a couple of issues in existing man pages
> Improve on man pages

- man/man8/swtpm_setup.pod
> man: Adjust and improve the man page for swtpm_setup

- samples/swtpm-localca.in
- tests/test_tpm2_samples_swtpm_localca
This PR backports a few swtpm-localca private key password related fixes.
> Backport swtpm-localca private key password related fixes

- samples/swtpm-localca.in
- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
- tests/test_tpm2_samples_swtpm_localca
This PR backports a few patches to stable-0.4.
> Backport a few patches to stable-0.4

- debian/swtpm-tools.install
- dist/swtpm.spec
- dist/swtpm.spec.in
Update the rpmspec for the swtpm-localca rewrite and create a swtpm-tools-pkcs11 package with the swtpm-create-tpmca script in it.
> Update rpmspec for swtpm-localca rewrite and create swtpm-tools-pkcs11 package

- CHANGES
- configure.ac
- debian/changelog
- dist/swtpm.spec
- dist/swtpm.spec.in
This PR prepares for the 0.4.1 release.
> Prepare for 0.4.1 release

- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
> swtpm_setup: Add missing --print-capabilities to help screen

- src/swtpm/swtpm_nvfile.c
- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
This PR backports two patches from master.
> Backport two patches

- CHANGES
- debian/changelog
- dist/swtpm.spec
- dist/swtpm.spec.in
This PR prepares for the 0.5.0 release.
> Prepare for 0.5.0 release

- man/man8/swtpm.pod
- man/man8/swtpm_cuse.pod
- src/swtpm/cuse_tpm.c
This PR adds support for the --flags options to the CUSE TPM.
> Support the --flags options in the CUSE TPM

- src/swtpm/swtpm_chardev.c
Lift the code that sets up the vtpm proxy device out of the main
function and put it into its own function.
> swtpm: Move setup of vtpm proxy device into own function

- samples/py_swtpm_localca/swtpm_localca.py
- samples/py_swtpm_localca/swtpm_utils.py
- src/swtpm/logging.c
- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
- src/swtpm_setup/py_swtpm_setup/swtpm_utils.py
This PR changes swtpm, swtpm_setup, and swtpm_localca from following symlinks.
> Prevent following a log file symlink

- .travis.yml
> Travis: Remove OSX CI/CD due to costs

- .travis.yml
- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
Backport the swtpm_setup increase of timeout from 10s to 30s for slower machines.
> swtpm_setup: Increase timeout from 10s to 30s for slower machines

- CHANGES
- configure.ac
- debian/changelog
- dist/swtpm.spec
- dist/swtpm.spec.in
- src/swtpm/pidfile.c
This PR prepares for the 0.5.2 release.
> Prepare for 0.5.2 relase

- man/man8/swtpm_bios.pod
- man/man8/swtpm_ioctl.pod
Modify the flag from "--unixio" to "--unix"
Signed-off-by: Lili Zhu <lizhu@redhat.com>
> Update the doc of the flag to connect to TPM via UnixIO socket

- man/man8/swtpm_bios.pod
- man/man8/swtpm_ioctl.pod
- src/swtpm/swtpm_chardev.c
- tests/test_tpm2_ctrlchannel2
>  Backport some bugfixes

- man/man8/swtpm_bios.pod
- man/man8/swtpm_ioctl.pod
- src/swtpm/swtpm_chardev.c
- tests/test_tpm2_ctrlchannel2
> Backport some bugfixes

- samples/setup.py
- src/swtpm/main.h
- src/swtpm_setup/setup.py
- tests/_test_setbuffersize
- tests/_test_tpm2_encrypted_state
- tests/_test_tpm2_setbuffersize
- tests/test_tpm2_ibmtss2
This PR fixes swtpm spelling errors reported in issue #410.
> Fix swtpm spelling errors reported in issue #410

- src/swtpm_ioctl/tpm_ioctl.c
Start using timeouts when communicating with swtpm over Unix sockets so
that swtpm_ioctl does not just hang when it cannot communicate with swtpm
such as establishing a connection or reading results. This is because swtpm
listens to nlye one control channel connections.
This patch addresses an aspect of the problem reported in issue #415
but may also starting hiding bugs if certain operations are done in
the wrong order, as was the case in libvirt (6.10 & 7.0).
> swtpm_ioctl: Use timeouts for communicating with swtpm (Unix socket)

- src/swtpm/common.c
> swtpm: Free error that was set by failed options_parse

- src/swtpm/swtpm_aes.c
This PR addresses a Coverity issue.
> Address a Coverity issue

- Makefile.am
- man/man8/Makefile.am
This PR has some fixes for the build-sys.
> Some fixes for the build-sys

- src/swtpm_setup/py_swtpm_setup/swtpm.py
- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
This PR fixes a couple of small issues in swtpm_setup.
> swtpm_setup: Fix a couple of small issues

- configure.ac
- src/swtpm_setup/swtpm.c
- src/swtpm_setup/swtpm_setup.c
- src/swtpm_setup/swtpm_setup_utils.c
- swtpm.spec
This PR backports some patches to 0.6 branch.
> Backport some patches to 0.6

- samples/swtpm_localca.c
- tests/test_tpm2_samples_create_tpmca
Add a missing else branch that was not translated from python
> swtpm-localca: Add a missing else branch that was not translated from python

- samples/swtpm_localca.c
- tests/test_tpm2_samples_create_tpmca
Add a missing else branch that was not translated from python.
> Backport: swtpm-localca: Add a missing else branch that was not translated from python 

- Makefile.am
- configure.ac
- run autoconf on configure.ac
- consolidate multiple .PHONY to avoid warning
> Fix some issues with the build system

- include/Makefile.am
- include/compiler_dependencies.h
- samples/swtpm_localca.c
- src/swtpm/Makefile.am
- src/swtpm/common.h
- src/swtpm/cuse_tpm.c
- src/swtpm/mainloop.c
- src/swtpm/swtpm_nvfile.c
- src/swtpm_bios/tpm_bios.c
- src/swtpm_cert/ek-cert.c
- src/swtpm_ioctl/tpm_ioctl.c
- src/swtpm_setup/swtpm_setup.c
This PR fixes a couple of issues raised when compiling with -Wextra.
> Fix a couple of issues raised when compiling with -Wextra

- src/swtpm/swtpm_nvfile.c
Add fsync(2) before rename(2) for temp file to ensure data reaches disk
and for directory which containing state file to ensure directory entry
also reaches disk.
> swtpm: Issue fsync to ensure state data reaches disk

- src/swtpm/tpmlib.c
- src/swtpm/utils.c
> swtpm: Fix issues raised by -Wextra (Cygwin)

- tests/_test_save_load_state
- tests/test_tpm2_parameters
This PR extends two test cases to increase the code coverage.
> Extend test cases to increase coverage

- INSTALL
> docs: Update INSTALL document

- configure.ac
- src/swtpm/Makefile.am
- src/swtpm_bios/Makefile.am
- src/swtpm_cert/Makefile.am
- src/swtpm_ioctl/Makefile.am
- src/swtpm_setup/Makefile.am
- src/utils/Makefile.am
This PR backports some recent fixes to the build system.
> Backport some cleanups to the build system

- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/swtpm_nvstore.c
- src/swtpm/swtpm_nvstore.h
> swtpm: Clear keys on heap at termination

- src/swtpm_setup/swtpm_setup.c
Currently swtpm_setup saves ek.cert and platform.cert to TPM state
directory and removes them later. As the usage of these files are
temporal, temp directory can be used for this purpose. This reduces
dependencies on TPM state dir, which is convenient for pluggable state
store (https://github.com/stefanberger/swtpm/issues/461).
> swtpm_setup: Use temp dir for certs instead of TPM state dir

- CHANGES
- debian/changelog
- src/swtpm/common.c
- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/swtpm_nvfile.c
- src/swtpm/swtpm_nvfile.h
- swtpm.spec
- swtpm.spec.in
> Prepare for release of v0.6.1

- .travis.yml
- configure.ac
- tests/test_setdatafd.py
Remove python-twisted usage in test used by python2 and also remove it from Travis. Remove the check for pip3 from configure.ac.
> Remove cruft

- CHANGES
> CHANGES: Adjust entry for building for OpenSSL 3.0

- src/swtpm/swtpm_nvstore.c
Add an implementation of SWTPM_HMAC using non-deprecated APIs when
compiling with OpenSSL 3.0.
This partially addresses issue #538.
> swtpm: Add implementation of SWTPM_HMAC using OpenSSL 3.0 APIs

- src/swtpm/swtpm_nvstore_dir.c
Only recent libvirt versions have the patch for the AppArmor profile
for libvirt to allow fsync on dir and directory. Rather than failing
hard on this error, log it once and continue and do not try fsync
again after.
This patch addresses the problems seen on Ubuntu related to an older
version of libvirt without the AppArmor profile update.
- issue #484
- issue #549
- issue #559
> swtpm: Make fsync() errors non-fatal (for libvirt using AppArmor)

- include/sys_dependencies.h
- src/swtpm/swtpm_nvstore_linear.c
- src/swtpm/swtpm_nvstore_linear_file.c
- src/swtpm_setup/swtpm.c
- src/swtpm_setup/swtpm_backend_file.c
- tests/test_tpm2_save_load_state_2_block
- tests/test_tpm2_save_load_state_2_linear
This PR fixes a couple of issues on non-Linux systems.
> Fix a couple of issue appearing on non-Linux systems

- src/swtpm_setup/swtpm.c
- src/swtpm_setup/swtpm_backend_file.c
This PR fixes some issues detected by Coverity
> Fix some issue detected by Coverity

- man/man8/swtpm.pod
- man/man8/swtpm_setup.pod
Add the version to items indicating when the feature was added.
Fix and unify some other ones.
> man: Add version when feature was added when missing fix some others

- src/swtpm/swtpm_nvstore.c
- src/swtpm_setup/swtpm.c
This PR addresses some issues detected by the (update) Coverity Scan
> Address issues detected by Coverity Scan

- samples/swtpm_localca.c
Avoid trying to create TPM certificates while the issuer certificate has
not been created, yet (in a 2nd step).
To resolve this do not just test for availability of the signing key, which
is created first, but also test for the issuer certifcate, which is created
in a 2nd step when the local CA is created. If either one is missing,
attempt to create the CA.
Resolves: https://github.com/stefanberger/swtpm/issues/644
> swtpm_localca: Test for available issuercert before creating CA

- CHANGES
- debian/changelog
- swtpm.spec
- swtpm.spec.in
> Prepare for release of v0.7.1

- CHANGES
- debian/changelog
- swtpm.spec
- swtpm.spec.in
> Prepare for release of v0.6.2

- man/man8/swtpm_setup.pod
- src/swtpm_localca/swtpm_localca_utils.c
- tests/test_swtpm_setup_create_cert
This PR resolves issues #663 and #664
> Fix issue with swtpm_setup and its man page

- CHANGES
- configure.ac
- debian/changelog
- man/man8/swtpm_setup.pod
- src/swtpm/daemonize.c
- src/swtpm_localca/swtpm_localca_utils.c
- swtpm.spec
- swtpm.spec.in
- tests/test_swtpm_setup_create_cert
Backport lost functionality for a 0.7.2 release
> Backport lost functionality for a 0.7.2 release

- CHANGES
- debian/changelog
- dist/swtpm.spec
- dist/swtpm.spec.in
> Prepare for v0.5.4 release

- configure.ac
This PR fixes a couple of issue in the configure.ac script.
> build-sys: Fix a couple of issue in the configure.ac script

- configure.ac
- dist/swtpm.spec
- src/swtpm/tlv.c
This PR backports a few patches from master.
> Backport a few patches for v0.5.5

- configure.ac
- src/swtpm/tlv.c
- swtpm.spec
This PR backports a few patches from master.
> Backport a few patches for v0.6.4

- CHANGES
- debian/changelog
- swtpm.spec
- swtpm.spec.in
> Prepare for v0.7.3 release

- configure.ac
- src/swtpm/swtpm_nvstore_dir.c
- swtpm.spec
Backport a patch from master to 0.7.4
> Backport a patch to 0.7.4

- src/swtpm/ctrlchannel.c
- src/swtpm/swtpm_nvstore_linear.c
- src/swtpm/tpmlib.c
- src/swtpm_bios/tpm_bios.c
- src/swtpm_cert/ek-cert.c
- src/swtpm_ioctl/tpm_ioctl.c
- src/swtpm_localca/swtpm_localca.c
- src/swtpm_setup/swtpm.c
- src/swtpm_setup/swtpm_setup.c
This PR resolves some issue that were reported by Coverity (non-web version).
None of the issues are so severe, some are memory leaks, others deal with NULL pointers returned from malloc (practically doesn't happen) or unnecessary code etc.
> Resolve some issues reported by Coverity

- src/swtpm/ctrlchannel.c
- src/swtpm/tpmlib.c
This PR contains minor clean patches
> Fix  a spelling error and remove wrong parameter from documentation

- src/swtpm/main.c
> swtpm: Update printed copyright notice

- src/swtpm_setup/swtpm_setup.c
> swtpm_setup: Add missing newline to help screen

- tests/_test_tpm2_save_load_state
> tests: Remove dump of logfile at end of test

- src/swtpm/cuse_tpm.c
Extend usage of the FILE_OPS_LOCK to prevent other threads from reading or
writing commands or doing ioctls while the current thread is reading a
response. This prevents a race condition where ptm_read_offset is set to 0
by a thread writing a new command to the device while the current thread
is reading a response from the device and needs this offset.
Resolves: https://github.com/stefanberger/swtpm/issues/725
> swtpm: cuse: Extend usage of FILE_OPS_LOCK to protect a reading thread

- src/swtpm/fips.c
- src/swtpm/seccomp_profile.c
This PR fixes some recently introduced build issues on some distros
> Fix some recenlty introduced build issues

- man/man8/swtpm.pod
- src/swtpm/capabilities.c
- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
- tests/test_tpm2_chroot_cuse
Adjust test case for nodev option and advertise --chroot option in capabilities
> Adjust test case for nodev option and advertise --chroot option in capabilities

- CHANGES
> CHANGES: Add documentation for changes in 0.8.0

- src/swtpm/options.c
> swtpm: Fix memory leak in case realloc fails

- src/swtpm_setup/swtpm.c
If swtpm_setup is configured with a log file, it launches swtpm configured with the same log file. If not, swtpm_setup logs will go to stdout/stderr and it should configure swtpm to do the same.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
> swtpm_setup: Configure swtpm to log to stdout/err if needed

- CHANGES
- debian/changelog
- swtpm.spec
- swtpm.spec.in
> Prepare for v0.8.0 release

- CHANGES
- debian/changelog
- dist/swtpm.spec
- dist/swtpm.spec.in
Prepare for release of swtpm-0.5.0
> Prepare for release of swtpm-0.5.0

- tests/Makefile.am
- tests/test_common
- tests/test_tpm2_save_load_state_3
> tests: Fix shellcheck issue SC2126 by using 'grep -c'

- tests/Makefile.am
- tests/_test_setbuffersize
- tests/_test_tpm2_derived_keys
- tests/_test_tpm2_file_permissions
- tests/_test_tpm2_setbuffersize
- tests/common
- tests/test_cuse
- tests/test_samples_create_tpmca
- tests/test_swtpm_setup_create_cert
- tests/test_swtpm_setup_overwrite
- tests/test_tpm12
- tests/test_tpm2_ibmtss2
- tests/test_tpm2_parameters
- tests/test_tpm2_samples_create_tpmca.test
- tests/test_tpm2_save_load_state_2
- tests/test_tpm2_save_load_state_2_block
- tests/test_tpm2_save_load_state_3
- tests/test_tpm2_swtpm_localca
- tests/test_tpm2_swtpm_localca_pkcs11.test
- tests/test_tpm2_swtpm_setup_create_cert
- tests/test_tpm2_swtpm_setup_overwrite
> tests: Fix shellcheck issue SC2143 by using grep -q

- tests/Makefile.am
- tests/common
- tests/load_vtpm_proxy
- tests/test_common
- tests/test_ctrlchannel
- tests/test_cuse
- tests/test_tpm2_swtpm_localca_pkcs11.test
This PR addresses issues with shellcheck SC2148, SC2010, and SC2001.
> Address 3 more cases of shellcheck issues

- tests/common
> tests: Fix shellcheck issue SC2148 by adding missing shell directive

- src/swtpm_ioctl/tpm_ioctl.c
Fix the display of long responses that require calling PTM_GET_INFO multiple times to get parts of the response from increasing offsets until the whole response has been received.
Long responses are only returned when libtpms has profiles support and several flags are passed to PTM_GET_INFO.
> swtpm_ioctl: Repeatedly call PTM_GET_INFO for long responses

- src/swtpm_setup/swtpm.c
In case swtpm does not start properly the write() to it may work but then the read() gets stuck. Detect a failed swtpm by adding a poll() before the read(). Use some extended durations considering possibly busy systems.
A terminating swtpm instance can be caused when an unacceptable profile is passed.
> swtpm_setup: Add poll() after write() and before read() to detect errors

- src/swtpm_setup/swtpm.c
- src/swtpm_setup/swtpm_setup.c
- src/utils/swtpm_utils.h
- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
This PR refactors and reformats code for easier future extensions
> Refactor and reformat for future extenions

- man/man8/swtpm_localca.pod
- src/swtpm_localca/swtpm_localca.c
- src/swtpm_setup/swtpm.c
See the patches for descriptions.
> Flush SPK for more room and introduce --key alias in swtpm_localca

- src/swtpm_ioctl/tpm_ioctl.c
Separate the return code returned from change_fd_flags from the current/ original flags of the file descriptor. Return the flags in an optional integer.
> swtpm_ioctl: Separate return code from flags

- CHANGES
- configure.ac
- debian/changelog
- src/swtpm/cuse_tpm.c
- swtpm.spec
- swtpm.spec.in
- tests/Makefile.am
swtpm v0.8.2 adds support for --disable-tests configure option.
> Prepare for swtpm v0.8.2

- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
> swtpm: fix typo in help message

- src/swtpm/swtpm_nvstore_dir.c
Since swtpm does not use concurrency while writing state files, set the process umask to 0 when the state file is created or truncated for writing and the user requested specific mode bits. This avoids an additional syscall in the possibly timing critical path when processing a TPM command and having to write the state.
> swtpm: Use umask() to create/truncated state file rather than fchmod()

- src/swtpm/check_algos.c
HMAC+sha1 may be restricted next, so test for it but do not support forced removal of support for it.
> swtpm: Implement a check for HMAC+sha1 for testing future restrictions

- man/man8/swtpm.pod
- man/man8/swtpm_setup.pod
- samples/swtpm_setup.conf.in
- src/swtpm/common.c
- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/tpmlib.c
- src/swtpm/utils.c
- src/swtpm_setup/swtpm.c
- src/swtpm_setup/swtpm.h
- src/swtpm_setup/swtpm_setup.c
- tests/test_tpm2_swtpm_setup_profile
Add support for reading a profile from a file to swtpm and swtpm_setup.
> Support reading a profile from a file

- src/swtpm_setup/swtpm_setup.c
When swtpm --print-capabilities for example fails to be able to access the log file that swtpm_setup logs into, then it may fail to run. In this case log the stderr output of swtpm.
> swtpm: Display stderr in case swtpm --print-capabilities failed

- src/selinux/swtpm_svirt.te
Link: https://bugzilla.redhat.com/show_bug.cgi?id=2334271
Resolves: https://github.com/stefanberger/swtpm/issues/964
> SELinux: Add rule for swtpm to be able to read password from pipe

- swtpm.spec.in
Suggested-by: Ajeeth Adithya <ajeeth.adithya@nutanix.com>
> swtpm.spec: Apply previous changes also to swtpm.spec.in

- CHANGES
- tests/patches/0011-Remove-unnecessary-include-of-openssl-engine.h.patch
- tests/test_tpm2_ibmtss2
Enable the IBMTSS2 test for swtpm 0.9.x.
> Enable the IBMTSS2 test 

- configure.ac
Cherry-pick changes from PR #1042 related to
- Changing of comment to start with dnl
- usage of PKG_CHECK_MODULES for dependent libraries that are required to be there
- Replacement of if test .. then .. else .. fi with AS_IF.
- Replacement of case statements with AS_CASE
- Reformatting to 4 spaces for indentation
> Cherry-pick parts from PR #1042

- configure.ac
Cherry-pick another round of changes related to:
- optional libraries: fuse/fuse3
- conversion to use PKG_CHECK_VAR
- conversion to use PKG_CHECK_MODULES
- conversion to use AS_IF
> Cherry-pick more parts from PR #1042

- .github/actions/test-swtpm/action.yml
Exit the build with an error code if memory leaks were detected.
> ci: Check logs for ASAN reporting memory leaks
