stefanberger/swtpm

- man/man8/swtpm.8
- man/man8/swtpm.pod
- man/man8/swtpm_cuse.8
- man/man8/swtpm_cuse.pod
- src/swtpm/Makefile.am
- src/swtpm/common.c
- src/swtpm/common.h
- src/swtpm/ctrlchannel.c
- src/swtpm/cuse_tpm.c
- src/swtpm/locality.h
- src/swtpm/mainloop.c
- src/swtpm/mainloop.h
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/tpmlib.c
- src/swtpm/tpmlib.h
- src/swtpm/vtpm_proxy.h
- tests/test_locality
Add options for locality handling so that commands in locality
4 for example are rejected per command line parameter. This is
useful when the vTPM is used with containers.
Also implement the custom TPM/TPM2_SetLocality command to allow
the Linux vTPM proxy driver to set the locality in which subsequent
TPM commands will be executed.
> Add options for locality handling and SetLocality command

- .travis.yml
- debian/control
- dist/swtpm.spec
- dist/swtpm.spec.in
- src/swtpm/ctrlchannel.c
- tests/test_clientfds.py
- tests/test_setdatafd.py
This patch series cleans up all python code to pass pep8 without complaints. It also removes a white space error in ctrchannel.c.
Switch the python test case that's sending the control and data message in two API calls to use the python twisted package to send it in one API call and avoid hacks on the server side.
> Cleanups and avoid race in test case

- run_tests
- src/swtpm_cert/ek-cert.c
- tests/Makefile.am
- tests/common
- tests/test_ctrlchannel
- tests/test_ctrlchannel2
- tests/test_parameters
- tests/test_vtpm_proxy
Enable testing of 32 bit and 64 bit executables with the test suite by allowing the path to the executable for swtpm, swtpm_ioctl, and swtpm_bios to be provided via variables. Add a test script that makes use of that.
> tests: Some work on the tests

- src/swtpm/ctrlchannel.c
- tests/Makefile.am
- tests/common
- tests/test_ctrlchannel
- tests/test_ctrlchannel3
- tests/test_ctrlchannel4
Convert and split some ctrlchannel related test cases so more tests can run on Cygwin as well.
Adapt the code related to CMD_SET_DATAFD in case of Cygwin.
> Convert some test cases and adapt code for Cygwin

- src/swtpm/ctrlchannel.c
Changeset aa3999 introduced a segfault when calling
ctrlchannel_set_client_fd() with a NULL pointer. Like all the other
functions, we return with -1 in this case.
> swtpm: fix segfault introduced in aa3999

- man/man8/swtpm_setup.8
- man/man8/swtpm_setup.pod
- src/swtpm_setup/swtpm_setup.sh.in
Add options --overwrite and --not-overwrite to allow or prevent
overwriting of existing TPM state. If neiter of the options is
given and existing state is found, an error is returned.
> swtpm_setup: Add options to overwrite or not overwrite TPM state

- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/utils.c
- src/swtpm/utils.h
Move some of the debugging output into its own function and
differentiate output by TPM Version number.
> swtpm: Move debugging output into own function

- .travis.yml
- tests/Makefile.am
- tests/common
- tests/test_tpm2_ibmtss2
Get the IBM TSS2 test suite from its git repo, compile it, and run
its test suite if SWTPM_TEST_EXPENSIVE=1 is set.
> tests: Get the IBM TSS2 test suite and run it

- src/selinux/swtpm_svirt.te
policy_module macro could be used here in declaration of swtpm_svirt SELinux module. This macro including all classes so there is no need for explicit require.
> Do few changes to follow distribution SELinux policy

- .travis.yml
- configure.ac
- src/swtpm/Makefile.am
- src/swtpm_bios/Makefile.am
- src/swtpm_cert/Makefile.am
- src/swtpm_ioctl/Makefile.am
- src/swtpm_setup/Makefile.am
This series of patches enables test coverage with gcc by using the configure option --enable-test-coverage. The test results are uploaded to Coverall.io at the end of a successful Travis run.
> Integration with Coverall.io

- dist/swtpm.spec
- dist/swtpm.spec.in
- src/swtpm_setup/Makefile.am
swtpm_setup.sh does not need to be owned by tss:tss and in the
Fedora package it's not even allowed. So remove the install hook
that was changing the ownership.
> swtpm_setup: Leave swtpm_setup.sh ownership to root

- src/swtpm_cert/ek-cert.c
Ceritficates for a TPM 2 have to be signed using SHA256 and those for
a TPM 1.2 have to be signed using SHA1 (following specs). We can use
either of these algorithms when using the GnuTLS TPM support since it
will create the hash and have the TPM 1.2 sign whatever it created.
> swtpm_cert: use hashAlgo as parameter for signing certificates

- tests/test_samples_create_tpmca
Extend the swtpm-create-tpmca test for covering the `--srk-well-known` support in tpmtool and actually create certificates and check whether their content.
> tests: Extend swtpm-create-tpmca test for --srk-well-known support

- samples/swtpm-create-tpmca
If tpmtool supports --srk-well-known we also support the well known
SRK password and allow the user not to provide an SRK password on
the command line.
This patch should have been applied before the previous patch that
tests this. Luckily, only very few systems have tpmtool with
--srk-well-known so that the order would matter there (and cause test
failures).
> samples: Enable support for well known SRK password (TPM 1.2)

- samples/swtpm-localca
- src/swtpm_cert/ek-cert.c
The following two patches add support for signing the EK and platform certs with pkcs11 modules' URIs.
> Add support for signing with pkcs11 modules' URIs

- autogen.sh
- configure.ac
Change the build system to create the m4 directory in autogen.sh and allow for missing NVRAM tools, which is the case for BSD and OS X as well.
> Support older systems, such as RHEL 6.

- debian/control
3 build dependencies were missing for a clean environment.
> debian: Add missing build dependencies

- .travis.yml
- debian/control
- dist/swtpm.spec
- dist/swtpm.spec.in
- samples/swtpm-localca.in
- tests/Makefile.am
- tests/softhsm_setup
- tests/test_tpm2_samples_swtpm_localca_pkcs11
This series of patches enable the signing of the TPM 1.2 or TPM 2.0 certificates with a key described by its pkcs11 URI.
> Enable and test pkcs11 keys to be used for signing TPM certificates

- .travis.yml
- tests/softhsm_setup
We need to run the softhsm/pkcs11 test case as root (sudo) under OS X
so that we can write the file /etc/gnutls/pkcs11.conf. However, once
we run the tests as root we cannot run the 'brew ls' command anymore
since it refuses to run with high privileges. So, if we run as root we
need to use sudo to switch to the nobody user to run the 'brew ls'
command that gives us the name of the softhsm pkcs11 module.
> Make softhsm/pkcs11 test case work on Travis on OS X

- tests/test_commandline
- tests/test_ctrlchannel3
Use wait_process_gone with 2 seconds timeout to wait for the swtpm to
have terminated after SIGTERM or connection loss. This avoids test
failures on slow Raspberry Pi 2.
> tests: Use wait_process_gone rather than sleep

- .travis.yml
- configure.ac
- debian/changelog
- dist/swtpm.spec
- dist/swtpm.spec.in
The extension of the travis.yml with the matrix broke the Coverity
submission. This patch fixes this. We have to build libtpms in
build_command_prepend since before_script now does something different.
We only build in task .1 and exit early on all the other ones if
we are using the coverity_scan git branch.
> Travis: Get Travis to submit to Coverity again

- samples/swtpm-localca.in
- src/swtpm_setup/swtpm_setup.sh.in
According to the XDG spec,
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html:
"If $XDG_CONFIG_HOME is either not set or empty, a default equal to
$HOME/.config should be used."
This fixes setting up a TPM with libvirt running in a user session.
When libvirt is running as a system instance, $HOME isn't set, so it
will fall back on @SYSCONFDIR@ (/etc usually)
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
> swtpm-setup: fallback on $HOME/.config

- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/utils.c
- src/swtpm/utils.h
Implement uninstall sighandlers to uninstall the signal handlers
and not to create another pipe.
> swtpm: implement uninstall_sighandlers

- configure.ac
If no prefix is passed to the configure line we get prefix=NONE
in evaluations of variables that depend on prefix at this point.
If the user provides no --prefix we assume /usr/local as the
default and override the 'NONE' value we have at this point.
> build-sys: Avoid prefix=NONE if no prefix is passed to configure

- tests/test_samples_create_tpmca
To prevent the test case from failing when an no --prefix is used
when configuring, use an empty options file via /dev/null. Otherwise
swtpm-localca starts looking for the options file in a place where
there is none.
> tests: Use an empty options file in case options file is accessed

- tests/Makefile.am
- tests/patches/lib.patch
- tests/test_tpm12
Add a test case that downloads the TPM 1.2 package from sourceforge,
patches a few files for OpenSSL compatibility, and runs a few test
cases of that test suite. Look for ERROR output in the test suite.
This test suite also provides better code coverage for libtpms.
> tests: Add test case running TPM 1.2 test suite

- tests/test_tpm12
- Clean up state files in case the test suite was interrupted
- Allow running it from the test directory by creating an absolute
path for TESTDIR so we can find the patch file; error out in
case the patching fails
- Run test case 2 and 1 as well but ignore ERROR output in case
of test 1. The errors stem from us not restarting the TPM when
the test suite asks for it.
> tests: Fix some issues with TPM 1.2 test

- tests/Makefile.am
- tests/patches/libtpm.patch
- tests/test_tpm12
Add test cases 25 and 26 and run test 25 with auditing enabled.
> tests: Add yet more tests for TPM 1.2 and enable auditing

- src/swtpm/utils.c
- tests/test_commandline
The return code of change_process_owner must be negative.
This patch fixes one occurrence.
> swtpm: Fix return code of change_process_owner

- src/swtpm/utils.c
- tests/test_ctrlchannel
This series of patches modifies an existing test case to use file descriptor passing for the pid file on platforms where this is supported and extends the support to OS X and adapts the test case to test there as well.
> Test file desciptor passing for pid file and extend support to OS X

- .travis.yml
Adjust directory and file ownerships so that we don't have to
run cpp-coveralls under sudo.
> travis: Run cpp-coveralls without sudo

- tests/common
When the PID_FILE is passed to swtpm as a file descriptor in one test,
we already create a file without content when running
'exec 100<>$PID_FILE'. So we have to extend wait_for_file to also
wait for file content since the 0.2 seconds delay are sometimes not
enough for content to have been written. Otherwise we do not get the
PID of the process. We can extend the function in this way since all
its usages imply that some content should become available.
> tests: wait for file content in wait_for_file

- src/swtpm/seccomp_profile.c
Add 9 more syscalls of concern to the seccomp profile blacklist.
> swtpm: Add 9 more syscalls to seccomp profile blacklist

- src/swtpm/options.c
Fix an illegal heap access while parsing the options by making
sure that we do not access the tok variable beyond its size
when comparing a character to '=' and later on when accessing
the value after the '='.
This bug was discovered by configuring as follows on Fedora 28:
CFLAGS="-fsanitize=address -g -ggdb" LIBS="-lasan" \
./configure --prefix=/usr
and running tests like this:
sudo bash -c "SWTPM_TEST_EXPENSIVE=1 make -j32 check"
The test case test_tpm2_ctrlchannel2 indicated the error.
It looks like gcc on Ubuntu Xenial on Travis did not detect this
error.
> swtpm: Fix illegal heap access while parsing options

- src/swtpm/seccomp_profile.c
- tests/Makefile.am
- tests/_test_tpm2_derived_keys
- tests/test_tpm2_derived_keys
Using the same initial state, the derived keys always have to be the
same.
> tests: Ensure that derived keys are always the same for the same state

- tests/_test_tpm2_derived_keys
Add a test case that tests the derivation of an EC key from the
primary key.
> tests: Add test case for deriving key from primary key

- tests/_test_tpm2_derived_keys
The old prime number generation algorithm also does not return
the same numbers on ppc64 (big endian) as on x86_64 or ppc64le,
so do not run the test there.
Signed-off-by: Stefan Berger <stefanb@linu.ibm.com>
> tests: Do not run key derivation test on ppc64

- man/man8/swtpm_setup.8
- man/man8/swtpm_setup.pod
- src/swtpm_setup/swtpm_setup.sh.in
- tests/test_parameters
Fix swtpm_setup support for passing passphrase via file descriptor by not stopping and restarting the TPM 1.2 but instead to use swtpm_ioctl to reinit the TPM 1.2.
> Fix swtpm_setup support for passing passphrase via file descriptor

- src/swtpm/mainloop.c
- src/swtpm/swtpm_io.c
- src/swtpm/swtpm_io.h
- src/swtpm/tpmlib.c
- src/swtpm/tpmlib.h
- tests/test_tpm2_ibmtss2
This series of patches add support for handling the data channel command prefixes that TCG uses in case of TPM 2.
> Add support for handling data channel command prefixes for TPM 2

- man/man8/swtpm.8
- man/man8/swtpm.pod
- man/man8/swtpm_cuse.8
- man/man8/swtpm_cuse.pod
- man/man8/swtpm_setup.8
- man/man8/swtpm_setup.pod
- src/selinux/swtpm_svirt.te
- src/swtpm/Makefile.am
- src/swtpm/capabilities.c
- src/swtpm/capabilities.h
- src/swtpm/common.c
- src/swtpm/common.h
- src/swtpm/ctrlchannel.h
- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm_setup/swtpm_setup.c
- src/swtpm_setup/swtpm_setup.sh.in
- tests/Makefile.am
- tests/_test_print_capabilities
- tests/common
- tests/test_print_capabilities
This series of patches adds support for the `--print-capabilities` command line option and addresses issue #143 .
> Add support for --print-capabilities command line option

- src/swtpm/ctrlchannel.c
- src/swtpm/key.c
- src/swtpm/logging.c
- src/swtpm/utils.c
- src/swtpm/utils.h
- tests/common
- tests/test_ctrlchannel
- tests/test_ctrlchannel2
- tests/test_tpm2_ctrlchannel2
Only some places for poll and read are handling the EINTR correctly
so far. Fix this now for the rest of poll/read/write's in use.
> swtpm: Handle EINTR for poll/read/write's

- .travis.yml
Only build the libtpms dir if it doesn't exist. When we do a Coverity
scan build it looks like we are now running the script afterwards as
well and this creates a build failure due to the 2nd clone.
> Travis: Only clone libtpms if libtpms dir does not exist

- tests/test_tpm2_ctrlchannel2
Fix spelling of call to function validate_pidfile
> tests: Fix spelling of call to function validate_pidfile

- src/selinux/swtpm_svirt.te
- src/swtpm/swtpm_io.c
There was an EIO error occurring when using 'swtpm chardev --vtpm-proxy' due to the `writev()`, which does not seem to work with a chardev.
Also Fedora 30 needs more SELinux rules.
> Fix a bug when using --vtpm-proxy and extend SELinux policy for F30

- src/selinux/swtpm_svirt.te
- src/swtpm/swtpm_io.c
There was an EIO error occurring when using 'swtpm chardev --vtpm-proxy' due to the writev(), which does not seem to work with a chardev.
Also Fedora 30 needs more SELinux rules.
> 0.2.0: Fix a bug when using --vtpm-proxy and extend SELinux policy for F30

- src/swtpm/swtpm_nvfile.c
> swtpm: Fix typo in error report: HMAC instead of hash

- src/selinux/swtpm_svirt.te
More rules are needed for QEMU and KVM type VMs on F30.
> SELinux: Need more rules for QEMU and KVM type of VMs on F30

- tests/common
If the test environment is running in a seccomp profile do not check
that the seccomp profile of the swtpm process runs with the action
provided in --seccomp action=... since the environment may override
this.
> tests: Skip seccomp check if env. sets up seccomp profile

- src/swtpm_cert/ek-cert.c
The OIDs for the TPM 1.2 and TPM 2 platform data
are different (though have the same name in the spec).
Adapt them for the TPM 2 case.
> swtpm_cert: Fix OIDs for TPM 2 platform data

- src/swtpm_cert/ek-cert.c
The OIDs for the TPM 1.2 and TPM 2 platform data
are different (though have the same name in the spec).
Adapt them for the TPM 2 case.
> swtpm_cert: Fix OIDs for TPM 2 platforms data

- .travis.yml
The Travis build on OsX was failing due to the following error:
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative': \
/usr/local/Homebrew/Library/Homebrew/global.rb:110: \
syntax error, unexpected keyword_rescue, expecting keyword_end (SyntaxError)
from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
The command "brew tap discoteq/discoteq" failed and exited with 1 during .
This patch resolves the issue.
> Travis: Work around failing OsX builds due to brew error

- tests/_test_print_capabilities
The test_print_capability is failing if SWTPM_EXE is for example
holding more than one parameter like 'valgrind ... /bin/swtpm' since the
variable was not protected with quotes. This patch fixes this.
> tests: Protect variable with executable with quotes

- .travis.yml
Since I am not often using the non-openssl crypto function usage
in libtpms, add a build to Travis that exercises the old code.
> Travis: Add asan build for non-openssl usage in libtpms

- INSTALL
Building the swtpm debian package the correct debian/shlibs.local stanza is
```
libtpms0 libtpms
```
The instructions in INSTALL add an extra space. I removed it.
> Fix a 1 letter typo in INSTALL instructions

- src/swtpm_ioctl/tpm_ioctl.c
> swtpm_ioctl: Fix uninitialized variable 'pgi'

- .travis.yml
- src/swtpm/swtpm_chardev.c
The --print-capabilities is missing in the 'swtpm chardev' help screen
but the code is there to interpret the command line flag. This patch
adds the missing lines to the help screen.
> swtpm: Add --print-capabilities to help screen of 'swtpm chardev'

- src/swtpm_setup/swtpm_setup.sh.in
Fix a cut and paste error in the error message output and be more
verbose in log about encryption when using file descriptors.
> swtpm_setup: Log about encryption and fix c&p error in err msg

- src/swtpm_setup/swtpm_setup.c
- src/swtpm_setup/swtpm_setup.sh.in
swtpm_setup.sh uses file descriptor 100 for 'exec 100 <> ...'.
So we have to make sure that the file descriptor inherited from
the caller of swtpm_setup does not overlap with a reserved range
to be used by swtpm_setup.sh, which we declare to be [100..110].
> swtpm_setup: Keep reserved range of file descriptors for swtpm_setup.sh

- src/swtpm_setup/swtpm_setup.sh.in
- tests/_test_init
- tests/_test_tpm2_init
- tests/common
- tests/test_commandline
- tests/test_vtpm_proxy
This series of patches fixes a few problems with test cases that allow one to now run all test cases with sudo and the executables wrapped with [Valgrind](https://github.com/stefanberger/swtpm/wiki/Using-Valgrind-to-detect-memory-leaks-and-other-errors).
> Enable test suite to run all tests with valgrind as root

- configure.ac
- debian/changelog
- debian/control
This series of patches fixes some issues reported by lintian that are related to the debian control file as well as issues related to the formatting of the changelog file.
Also, the check for libseccomp was not reporting 'yes' or 'no', so fix this as well.
> Fix some issues for the debian build

- configure.ac
- debian/changelog
- debian/control
- tests/_test_init
- tests/_test_tpm2_init
- tests/common
- tests/test_clientfds.py
- tests/test_commandline
- tests/test_ctrlchannel
- tests/test_ctrlchannel2
- tests/test_ctrlchannel3
- tests/test_ctrlchannel4
- tests/test_parameters
- tests/test_samples_create_tpmca
- tests/test_swtpm_setup_create_cert
- tests/test_tpm2_ctrlchannel2
- tests/test_tpm2_parameters
- tests/test_tpm2_save_load_state_3
- tests/test_tpm2_swtpm_setup_create_cert
- tests/test_tpm2_vtpm_proxy
- tests/test_vtpm_proxy
These fixes are mostly related to the Ubuntu PPA build for which we need SWTPM_TEST_SECCOMP_OPT to override the fault environment that cannot deal with seccomp profiles.
> Merge some fixes

- tests/_test_init
- tests/_test_tpm2_init
- tests/common
- tests/test_clientfds.py
- tests/test_commandline
- tests/test_ctrlchannel
- tests/test_ctrlchannel2
- tests/test_ctrlchannel3
- tests/test_ctrlchannel4
- tests/test_parameters
- tests/test_samples_create_tpmca
- tests/test_swtpm_setup_create_cert
- tests/test_tpm2_ctrlchannel2
- tests/test_tpm2_parameters
- tests/test_tpm2_save_load_state_3
- tests/test_tpm2_swtpm_setup_create_cert
- tests/test_tpm2_vtpm_proxy
- tests/test_vtpm_proxy
The Ubuntu (PPA) build system executes the build on an environment that
has problems with seccomp profiles. It does not allow us to run the test
suite with swtpm applying its seccomp profile since it fails with a
'bad system call' error. To work around this we introduce the env. variable
SWTPM_TEST_SECCOMP_OPT that we can set to "--seccomp action=none" to avoid
having swtpm apply it seccomp profile.
> tests: Allow seccomp override w/ SWTPM_TEST_SECCOMP_OPT env var

- src/swtpm_setup/swtpm_setup.sh.in
swtpm_setup will fail once libtpms starts supporting other PCR
hash banks than sha1, sha256, sha384, sha512, and sm3-256. So,
this patch allows to choose active PCR banks of the SHA3 series.
Further, unknown hash banks will not fail the tool anymore when
it tries to determine which hash banks are supported by the TPM
since it will then add the hex number of the hash algorithm to
the collection of supported hashes.
> swtpm_setup: Allow choices of future PCR bank hashes

- src/swtpm/mainloop.c
- src/swtpm_bios/tpm_bios.c
- src/swtpm_ioctl/tpm_ioctl.c
This series of patches fixes a couple of issues related to closed pipes. swtpm_ioctl and swtpm_bios need to ignore SIGPIPE so they can receive EPIPE from a failing write()/writev(). 
Swtpm should no accept any new control channel connections while it still has a control channel client but wait until this client has closed, otherwise we may end up closing the new control channel client's fd if poll() indicated that the previous client closed the connection.
> Sigpipe fixes

- src/swtpm/mainloop.c
Only accept new client connection on the control channel if we
currently do not have a client on the control channel.
> swtpm: Only accept() new client ctrl connection if we have none

- samples/swtpm-create-tpmca
- samples/swtpm-localca.in
- src/swtpm_setup/swtpm_setup.sh.in
- tests/common
- tests/test_samples_create_tpmca
- tests/test_tpm2_samples_swtpm_localca
- tests/test_tpm2_swtpm_setup_create_cert
Fix serveral issues in the shell scripts reported by shellcheck. We can now use file paths that have spaces in them.
> Enable spaces in paths

- tests/test_commandline
Give swtpm more time to close the port. This became an issue when running
the tests and all executables are valgrind'ed.
> tests: Wait longer for port to close when running with valgrind

- src/swtpm/tpmlib.c
> swtpm: Only call memcpy if tocopy != 0 (coverity)

- src/swtpm/swtpm_chardev.c
- tests/test_vtpm_proxy
'swtpm chardev --vptm-proxy' currently requires a '--flag startup-xyz'
to be passed since otherwise the need_init_cmd variable would not be
set to false. To maintain backwards compatibility we have to always
set the need_init_cmd variable to false for the --vtpm-proxy case.
Roll back one of the test case to not use the startup flag.
Fixes: e6bc4bdf0 ('swtpm: Enable sending startup commands ...')
> swtpm: Fix vtpm proxy case without startup flags

- .travis.yml
Allow specifying a libtpms revision to test with, defaulting to
master branch.
Have the OS X test use the stable-0.6.0 branch.
> Travis: Checkout a certain libtpms revision

- tests/test_tpm2_ibmtss2
Upgrade to use the IBM TSS2 test from v1.4.0 but eliminate all testing
with 3072 bit RSA keys.
> tests: Use the IBM TSS2 v1.4.0's test suite

- run_tests
- tests/_test_tpm2_derived_keys
This series of patches allows to run run_test.sh on x86_64 hosts again. It needed better detection of a 32 bit swtpm for which the test_tpm2_derived_keys had to skip certain tests for which we only have expected return values for 64bit swtpm's.
> Enable run_test.sh on x86_64 again due to better detection of 32 bit swtpm

- run_tests
Previous commit broke the run_test script and only ended up running
the first test. This  patch fixes it and displays an success message
at the end.
> tests: Run all tests again in run_test

- tests/test_tpm2_save_load_state_3
Create orderly NVRAM indices and then clear the TPM 2 so that NvDeleteRam()
gets executed and we get better code coverage.
> tests: Create orderly NVRAM indices and then clear TPM 2 (for coverage)

- src/swtpm/key.c
Compilation on cygwin reports the following issue:
In file included from key.c:43:
key.c: In function ‘key_stream_to_bin’:
key.c:135:26: error: array subscript has type ‘char’ [-Werror=char-subscripts]
135 |            !isspace(input[digits]) &&
|                     ~~~~~^~~~~~~~
key.c:143:40: error: array subscript has type ‘char’ [-Werror=char-subscripts]
143 |     if (input[digits] && !isspace(input[digits]))
|                                   ~~~~~^~~~~~~~
Address the issue using an explicit cast of char to int.
> swtpm: Address cygwin compilation warning

- src/swtpm/seccomp_profile.c
Add some recent syscalls to the seccomp blacklist, particularly
setter type of functions.
> swtpm: Add some recent syscalls to seccomp blacklist

- tests/_test_tpm2_derived_keys
Use 'cp -f' to force-copy over existing files. This solves an issue
seen only on Travis.
> tests: Use 'cp -f' for copying over existing files (Travis issue)

- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
It's not necessary anymore to #include <seccomp.h> from the main programs.
Once removed, it also fixes the build on SuSE where seccomp.h is in
seccomp/seccomp.h and we didn't use the LIBSECCOMP_CFLAGS for swtpm.c etc.
> swtpm: Remove unnecessary #include <seccomp.h> (fixes SuSE build)

- tests/test_tpm2_save_load_state_3
Revert the accidental port change from commit 0194fb22a.
> tests: Revert accidental port change from commit 0194fb22a

- tests/Makefile.am
- tests/_test_tpm2_print_capabilities
- tests/test_tpm2_print_capabilities
Add a test case testing the returned value from
swtpm <iface> --tpm2 --print-capabilities
along with those return from swtpm_setup.
> tests: Add test case for 'swtpm <iface> --tpm2 --print-capabilities'

- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
Invoke the printing of the capabilites after choosing the TPM version
in libtpms.
> swtpm: Invoke print capabilites after choosing TPM version

- tests/test_tpm12
Sometimes the download of the TPM 1.2 test suite from sourceforge
fails. So retry up to 3 times and wait a random seconds in the interval
of [3..10] before retrying.
Check the hash of the file we downloaded to make sure we get what we
expected.
> tests: Repeat download of TPM 1.2 test suite with random wait intervals

- src/swtpm/tpmlib.c
Handle the default cases, which shouldn't ever be reachable, and set
the tocopy to '0' so that no unitialized variable gets copied.
> swtpm: Make coverity happy by handling default case in case statement

- tests/test_tpm2_save_load_state_2
tssgetcapability only retrieves a maximum of 64 handles by default.
However, there are 65 persisted keys. Pass -pc 80 to the command to
see all 65 Handles.
> tests: Pass -pc 80 to tssgetcapability to see all 65 handles

- src/swtpm_setup/swtpm_setup.sh.in
This PR now introduces NIST P384 key creation code and ditches NIST P256 related code. It also changes swtpm_setup so that now an RSA as well as a NIST P384 EK key are created.
> Support PC Client Platform TPM Profile Specification for TPM 2.0 V1.04, rev 37

- src/swtpm_setup/swtpm_setup.sh.in
Remove tpm2_stirrandom, which we should not need to run on a newly
created TPM 2.
Also remove tpm2_changeeps which was called twice when creating two
EKs, thus invalidating a previous EK that may have been created
using --ecc.
> swtpm_setup: bugfix: remove tpm2_stirrandom and tpm2_changeeps

- src/swtpm_setup/swtpm_setup.sh.in
Return the result of the called function rather than 0.
Fixes: d65f5ae1 ("swtpm_setup: Create RSA 2048 and ECC NIST P256 keys and certs")
> swtpm_setup: return result of called function rather than 0

- src/swtpm_setup/swtpm_setup.sh.in
The ECC storage primary key was mistakently created in the endorsement
hierarchy but should be in the owner hierarchy. This patch corrects this
to have this key created in the owner hierarchy (like the RSA key),
thus using 0x40 00 00 01.
This only mattered if one used --create-spk and --ecc together.
> swtpm_setup: bugfix: Create ECC storage primary key in owner hierarchy

- man/man8/swtpm.8
- man/man8/swtpm.pod
- src/swtpm/capabilities.c
- tests/_test_tpm2_print_capabilities
- tests/test_tpm2_ibmtss2
Have swtpm report libtpms's RSA key size capabilities and use it to adapt test cases so that we run RSA 3072 test cases when libtpms supports them.
> Have swtpm report RSA key size capabilities and use to adapt test cases

- man/man8/swtpm_setup.8
- man/man8/swtpm_setup.pod
- src/swtpm_setup/swtpm_setup.c
- src/swtpm_setup/swtpm_setup.sh.in
- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
- tests/test_tpm2_parameters
- tests/test_tpm2_swtpm_setup_create_cert
This pull request adds support for RSA 3072 keys by
- testing that a vTPM that has been filled up with RSA 2048 bit keys can still be loaded into a libtpms that support RSA 3072 bit keys; the problem is especially related to the size of the TPM 2 OBJECT type that has increased due to RSA 3072 support and now the NVRAM needs more space
- having swtpm and swtpm_setup advertise RSA 3072 bit key support via --print-capabilities
- supporting RSA 3072 bit EK keys via swtpm_setup
- extending swtpm_setup test cases to cover RSA 3072 bit keys
> Add support for RSA 3072 keys

- configure.ac
Building things like this in-place is really useful when you can't be
bothered to package and install them for your distribution but still
want to use them.  This patch allows building swtpm with libtpms in
place.  Simply specify the location to LDFLAGS and CFLAGS on the
configure line
LIBTPMS_CFLAGS=-I/home/jejb/git/libtpms/include/ LIBTPMS_LDFLAGS=-L/home/jejb/git/libtpms/src/.libs/ ./configure
It will then build a version that can run in-place.
I also think it corrects a bug in the original in that if pkg-config
had specified a non standard library location, the version check
wouldn't have used it.
Signed-off-by: James E.J. Bottomley <jejb@linux.ibm.com>
> build-sys: Let swtpm build with in-place libtpms

- src/swtpm_setup/swtpm_setup.sh.in
This PR fixes two issues with 3072 bit EK keys:
-  put them into the correct NVRAM location
-  create the RSA EK key with an empty nonce buffer rather than 384 bytes of zeroes
> Fix issues with RSA 3072 bit EK keys

- tests/_test_tpm2_derived_keys
The first part of the derived key test only works fine on 64 bit
little endian machines. Skip big endian machines.
> tests: Skip derived key test 1st part on big endian machines

- tests/_test_tpm2_encrypted_state
- tests/_test_tpm2_hashing3
- tests/_test_tpm2_save_load_encrypted_state
- tests/_test_tpm2_savestate
- tests/_test_tpm2_volatilestate
- tests/test_tpm2_ctrlchannel2
- tests/test_tpm2_vtpm_proxy
libtpms version 0.6.3, 0.7.3, and master have a change to the TPM 2 code
that affects the pcrUpdateCounter, which now returns a smaller value than
before.
> tests: Adapt test cases' expected PCR result due to libtpms TPM 2 fix

- debian/changelog
- debian/swtpm-cuse.install
- debian/swtpm-tools.postinst.in
Remove swtpm_cuse related install script since not needed anymore.
Also address the following issues:
E: swtpm-tools: unknown-control-interpreter control/postinst #!/usr/bin/env
W: swtpm: syntax-error-in-debian-changelog line 25 "bad key-value after `;': `urgency medium'"
> debian: Address some issues raised by lintian

- tests/Makefile.am
- tests/patches/ibmtss2_1.5_rsa2048only.patch
- tests/test_tpm2_ibmtss2
Upgrade to use the IBM TSS2 tests from v1.5.0.
Add a patch that eliminates all testing of 3072 bit RSA keys in case
libtpms does not support such keys. This test also passes with libtpms
0.6.0 and 0.7.0.
> tests: Use the IBM TSS2 v1.5.0's test suite

- configure.ac
- src/swtpm/Makefile.am
This PR fixes 2 build system issues when clang is used and compilation is done on Gentoo:
- testing for unused linker flags that lead to compilation errors when -Werror is usded
- explicitly link libswtpm_libtpms.so with -lcrypto to avoid unresolved issues
> Fix build system issues for clang

- configure.ac
- src/swtpm_setup/swtpm_setup.sh.in
This PR fixes a few issues related to requirements of the tcsd on file modes and ownership of the tcsd config file for distros that do NOT use tss:tss as user/group for the tcsd config file but root:tss (openSUSE). Ubuntu and Fedora for example use tss:tss due to the configuration of the tcsd there.
> swtpm_setup fixes for distros not using tss:tss for tcsd user/group

- configure.ac
A typo in the condition meant that `netstat` was always required regardless of whether `tcsd` is available or not.
> build-sys: fix test for netstat if tcsd is not available

- tests/test_tpm2_samples_swtpm_localca
- tests/test_tpm2_samples_swtpm_localca_pkcs11
The generated sample keys started with 00010203, thus leaving the
upper 15 bits of the key as '0', which in turn causes gnutls to think
that the key is only 2033 bit long, thus rejecting certificate
verification once the min-verification-profile is set to 'medium'
in /etc/crypto-policies/back-ends/gnutls.config.
This fixes test errors on Fedora Rawhide due to the change in
the min-verification-profile setting in gnutls.config.
> tests: Modify sample key to be 2048 bit rather than 2033 bit

- tests/test_tpm2_samples_swtpm_localca
- tests/test_tpm2_samples_swtpm_localca_pkcs11
The generated sample keys started with 00010203, thus leaving the upper
15 bits of the key as '0', which in turn causes gnutls to think that the
key is only 2033 bit long, thus rejecting certificate verification once
the min-verification-profile is set to 'medium' in gnutls's config file
in /etc/crypto-policies/back-ends/gnutls.config.
We now create sample keys starting with 800102, which sets the highest bit.
This fixes test errors on Fedora Rawhide due to the change in the
min-verification-profile setting in gnutls.config.
> tests: Modify sample key to be 2048 bit rather than only 2033 bit

- tests/test_tpm2_samples_create_tpmca
Have the tpm2_ptool use a store in the temporary directory so that
with every test we have a clean environment.
> tests: Have tpm2_ptool use store in temporary directory

- man/man8/swtpm_setup.pod
> man: Add missing -- to --rsa-keysize in documentation

- src/swtpm/logging.c
> swtpm: Change include of sys/fcntl.h to fcntl.h

- Makefile.am
- src/selinux/Makefile.am
Add build targets selinux-install and selinux-uninstall to install
and uninstall the SELinux policy rules at a given priority. The
priority defeaults to 400, which works fine on Fedora.
> build-sys: Add build targets selinux-install and selinux-uninstall

- src/selinux/Makefile.am
When running the selinux-install target also label swptm and swtpm_cuse.
> build-sys: Label swtpm and swtpm_cuse with SELinux label

- tests/_test_tpm2_save_load_state_da_timeout
We have occasional test failures on Travis running tests on OS X where
time seems to be going backwards in the dictionary attack timeout test.
This patch tries to detect that the time went backwards and skip the
test once a failure would have been detected.
This PR (hopefully) fixes issue #249.
> tests: Skip test if time was detected to be going backwards

- src/swtpm_setup/swtpm_setup.sh.in
BSD's sed does not print \n as newline, so we have to split the string
into different lines using tr.
> swtpm_setup: Accomodate for BSD sed that does not print \n as newline

- configure.ac
- tests/test_parameters
This PR fixes some minor issues such as checking for the flock tool and a fix for BSD where `od` output needs to be 'squeezed.'
> Some fixes of minor issues

- tests/softhsm_setup
- tests/test_tpm2_samples_swtpm_localca_pkcs11
Extend softhsm_setup to be able to use a temporary directory for storing the softhsm configuration file and state. Use this in the test case so we can leave the local user's softhsm configuration alone.
> Tests: Extend softhsm_setup to be able to use a temporary directory and is it in test

- configure.ac
- debian/changelog
- dist/swtpm.spec
> build-sys: Bump up version to 0.5.0 at beginning of dev cycle

- configure.ac
- src/swtpm/Makefile.am
Clang complains if eiher one of those linker flags are used during compilation:
clang-9: error: -Wl,-z,relro: 'linker' input unused [-Werror,-Wunused-command-line-argument]
clang-9: error: -Wl,-z,now: 'linker' input unused [-Werror,-Wunused-command-line-argument]
This patch applies those flags only when linking.
> build-sys: Use -Wl,-z,relro and -Wl,-z,now only when linking (clang)

- configure.ac
- src/swtpm_setup/Makefile.am
Distributions often have their own guidelines regarding installation of Python modules (e.g. Arch Linux [mandates using `--optimize=1`](https://wiki.archlinux.org/index.php/Python_package_guidelines#distutils) for `setup.py install`, which the Makefile in this project [does not do](https://github.com/stefanberger/swtpm/blob/0c238a2c93cdeea4283c6e9a7b8430a9b2df2b3e/src/swtpm_setup/Makefile.am#L39)). Add an option `--disable-python-installation` (disabled by default) to allow skipping the Python installation process entirely so that distributions can take care of this process manually in their preferred way.
> build-sys: add configure option to disable installation of Python module

- samples/swtpm-localca.in
- tests/test_tpm2_samples_swtpm_localca
This PR fixes some usage aspects for passwords for the private keys of the localca. The create signing key was not properly protected with the password and when creating the platform certificate the password for the signing key was not used.
> samples: Fix usage of passwords for private keys

- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
During the rewrite the additonal "/.config/" got dropped from the
path when using ${HOME} for locating he default config file.
Re-add it.
> swtpm_setup: Add missing .config path when using ${HOME}

- samples/py_swtpm_localca/swtpm_localca.py
Older versions of GnuTLS need --password on the command line while
newer versions require GNUTLS_PIN to be set to pass the password.
So, this patch accomodates older versions of GnuTLS.
Older version of GnuTLS seem to NOT be able to handle a CA private
key needing a password and a signing key needing a password when
creating the intermediate CA. So this case of 2 passwords will
always fail.
The value of the local CA is not so high that passing passwords on
the command line would be an issue. Later on when using the CA the
password are set via environment variables, so not visible to other
users.
> samples: Add --password parameter for older GnuTLS versions

- samples/py_swtpm_localca/swtpm_localca.py
- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
This PR fixes support for the short options -h and -? in swtpm-localca and swtpm_setup.
> Fix support for the short options -h and -? in swtpm-localca and swtpm_setup

- man/man8/swtpm-localca.pod
- samples/py_swtpm_localca/swtpm_localca.py
Pass the CA's private key password via the template file. Remove recently
added old GnuTLS support. Extend man page with a paragraph about short-
comings of certtool that doesn't seem to allow private key password being
passed either as environment variable or template file.
> samples: swtpm-localca: Pass password via template file when possible

- tests/test_tpm2_samples_create_tpmca
Start tpm2-abrmd for the test case 'test_tpm2_samples_create_tpmca' rather than
expecting it to be already running.
> tests: start tpm2-abrmd for test case

- samples/swtpm-create-user-config-files.in
When creating the user config files, fall back to using ${HOME}/.config
if XDG_CONFIG_HOME is not set on a system.
> samples: Use ${HOME}/.config if XDG_CONFIG_HOME is not set (RHEL)

- configure.ac
> fix LDFLAGS for non-standard libtpms location

- src/swtpm_setup/swtpm_setup.c
passwd is always NULL since recent changes and the removed part
is basically always dead.
> swtpm_setup: Remove dead code part

- src/swtpm/ctrlchannel.c
- src/swtpm/swtpm_debug.c
- src/swtpm/swtpm_debug.h
- src/swtpm/swtpm_io.c
To avoid clashes with libtpms print functions, prefix the print function
in swtpm with SWTPM_ rather than TPM_. This may matter on older systems
where libtpms could call into swtpm's TPM_PrintAll function due to it
having the same name as libtpms's function.
> swtpm: Prefix debug print function with SWTPM rather than TPM

- configure.ac
- tests/common
Some distros (openSUSE) have deprecated the 'net-tools' package,
so we allow for 'ss' as an alternative tool from the
iproute/iproute2 package. This is only relevant for test cases.
> tests: Allow 'ss' as an alternative to 'netstat'

- src/swtpm/swtpm_nvfile.c
To support writing state files atomically we first write into
a temporary file and then rename it.
> swtpm: Write state files atomically using file renaming

- tests/test_samples_create_tpmca
This patch fixes the path to swtpm-localca to avoid this type of
error because of swtpm_localca_conf having been created in another
directory. This error occurred whan running
sudo bash -c "make -j32 distcheck"
Traceback (most recent call last):
File "/home/stefanb/tmp/swtpm/swtpm-0.5.0/samples/swtpm-localca", line 5, in <
from py_swtpm_localca.swtpm_localca import main
File "/home/stefanb/tmp/swtpm/swtpm-0.5.0/samples/py_swtpm_localca/swtpm_local
from py_swtpm_localca.swtpm_localca_conf import SYSCONFDIR
ModuleNotFoundError: No module named 'py_swtpm_localca.swtpm_localca_conf'
> tests: Fix path to swtpm-localca

- Makefile.am
- samples/Makefile.am
- src/swtpm_setup/Makefile.am
To force the installation of the python programs add a python-install
target. This solves an installation issue with non-standard prefix,
like not using /usr or /usr/local, as may be the case on OS X (Apple)
when using homebrew. It leaves the 'make distcheck' working, which also
uses a non-standard prefix and where we don't want to install the tools
due to issues with removing them afterwards where pip3 cannot be used.
> build-sys: Add python-install and python-uninstall targets

- samples/py_swtpm_localca/swtpm_localca.py
- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
- swtpm-localca and swtpm_setup after the re-write were now trucating the log file; do not truncate it
- swtpm_setup now removes the TPM state file in case an error occurred while running
> Fix some issues in the python programs

- debian/changelog
Confer:
```
$ dpkg-buildpackage -us -uc
dpkg-buildpackage: info: source package swtpm
dpkg-buildpackage: info: source version 0.5.0-1
dpkg-buildpackage: info: source distribution RELEASED
dpkg-buildpackage: info: source changed by Stefan Berger <stefanb@linux.ibm.com>
dpkg-source: error: can't build with source format '3.0 (native)': native package version may not have a revision
```
> debian: drop revision from version, illegal for native-format packages

- configure.ac
- debian/changelog
- dist/swtpm.spec
- samples/swtpm-create-user-config-files.in
This PR adds a --root flag to swtpm-create-user-config-files and adjusts the package version to 0.6.0.
> Add --root flag to swtpm-create-user-config-files

- tests/test_samples_create_tpmca
Due to recent changes in tcsd, it doesn't accept 'tss:tss 0600' anymore
for the tcsd config file but we need to use 'root:tss 0640' for it.
So far only Fedora seems to be affected. It now depends on whether tcsd
has been patched what ownership is required. So we try first the old
configuration and then the new one.
> tests: Try with tcsd.conf ownership of root:tss if tss:tss did not work

- configure.ac
Currently it shows "python setuptools is required" if "import cryptography" failed.
> build-sys: fix configure python cryptography error message

- src/swtpm/pidfile.c
- src/swtpm/swtpm_nvfile.c
- src/swtpm_cert/ek-cert.c
This PR gets rid of the fopen() call and switches over to the open() call. Along with this we are now using O_NOFOLLOW whenever we open a file for writing to avoid symlink attacks.
> Use open() call rather than fopen() and avoid following symlinks

- CHANGES
- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
- src/swtpm_setup/py_swtpm_setup/swtpm_utils.py
This PR changes swtpm and swtpm_setup from following symlinks when accessing the log file for writing.
> Prevent following a log file symlink

- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
Older ARM processors need more time to create the initial CA keys
and then the key for the TPM. So we increase the timeout to 30s.
> swtpm_setup: Increase timeout from 10s to 30s for slower machines

- src/swtpm/ctrlchannel.c
This patch fixes the following compilation issue/bug:
ctrlchannel.c: In function ‘ctrlchannel_process_fd’:
ctrlchannel.c:694:13: error: array subscript ‘ptm_hdata[0]’ is partly outside array bounds of ‘struct output[1]’ [-Werror=array-bounds]
694 |         data->u.resp.tpm_result = htobe32(res);
|             ^~
ctrlchannel.c:486:7: note: while referencing ‘output’
486 |     } output;
|       ^~~~~~
Sending hashes to the TPM is not currently used in any major
application, so this bug should not affect much.
> swtpm: Adjust size of message buffer to be of size ptm_hdata

- src/swtpm/pidfile.c
Do not bother trying to keep pidfilefd open in case fd = pidfilefd,
but close it unconditionally. If writing the pidfile fails, the process
terminates anyway, besides that we only ever need to write to the
pidfile once, which is happening in this function.
> swtpm: Unconditionally close fd if writing of pidfile fails (coverity)

- src/swtpm/pidfile.c
Since the pidfilefd will be closed, set it to -1 if it's being
used.
> swtpm: Set pidfilefd to -1 when used

- man/man8/swtpm_ioctl.pod
- src/swtpm_ioctl/tpm_ioctl.c
This PR adjusts the man page of swtpm_ioctl to reflect that the device parameter is optional.
We also remove an unnecessary if statement in swtpm_ioctl.c.
> swtpm_ioctl: Adjust man page and remove unnecessary if statement

- src/swtpm/ctrlchannel.c
- src/swtpm/key.c
> swtpm: Remove global unused variable input (issue #395)

- src/swtpm/cuse_tpm.c
- src/swtpm/threadpool.c
Asan reports this error for the CUSE TPM. The file_ops_lock was accidentally
duplicated in a code move of threadpool related code out of cuse_tpm.c
This patch removes the unused file_ops_lock from threadpool.c to resolve
the ASAN issue.
=================================================================
==545493==ERROR: AddressSanitizer: odr-violation (0x000000419340):
[1] size=8 'file_ops_lock' cuse_tpm.c:112:8
[2] size=8 'file_ops_lock' threadpool.c:55:8
These globals were registered at these points:
[1]:
#0 0x14f6c27f3cc8  (/lib64/libasan.so.6+0x37cc8)
#1 0x40c2c3 in _sub_I_00099_1 (/home/stefanb/tmp/swtpm/src/swtpm/.libs/lt-swtpm+0x40c2c3)
#2 0x40c31c in __libc_csu_init (/home/stefanb/tmp/swtpm/src/swtpm/.libs/lt-swtpm+0x40c31c)
[2]:
#0 0x14f6c27f3cc8  (/lib64/libasan.so.6+0x37cc8)
#1 …
> swtpm: Remove unused file_ops_lock from threadpool.c (asan)

- src/swtpm/cuse_tpm.c
- tests/Makefile.am
- tests/test_tpm2_partial_reads
This patch adds support for partial reads to the CUSE swtpm.
We introduce a ptm_read_offset variable that holds the offset where to read
from next. It is reset every time a command has been processed as part of a
write() so that subsequent read()s start reading from offset 0. It is
advanced by the number of bytes that were read.
> swtpm_cuse: Support parial reads (issue #376)

- src/swtpm/swtpm_chardev.c
- tests/test_tpm2_ctrlchannel2
This patch fixes the following issue:
$ ./src/swtpm/swtpm chardev --print-capabilities --tpm2
swtpm: Error: Missing character device or file descriptor
> swtpm: Fix --print-capabilities for 'swtpm chardev'

- configure.ac
We need at least 2.1.x, 2.1.4, that supports OAEP.
> build-sys: Check for python cryptography version

- .travis.yml
Pip 21.0.0 seems to be broken when upgraded to on Xenial. So
let's just only upgrade to 20.3.3.
$ sudo pip3 install --upgrade cryptography
Traceback (most recent call last):
File "/usr/local/bin/pip3", line 7, in <module>
from pip._internal.cli.main import main
File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
sys.stderr.write(f"ERROR: {exc}")
> Travis: Upgrade pip to v20.3.3

- src/swtpm_setup/py_swtpm_setup/swtpm.py
We need to probe for the support socketpair() domain. On Linux only
socket.AF_UNIX is support and on Cygwin AF_INET works.
> swtpm_setup: Probe for supported socketpair socket domain (cygwin bugfix)

- src/swtpm_setup/py_swtpm_setup/swtpm.py
A wrong domain to socketpair() causes a ValueError, not an OSError.
> swtpm_setup: Replace OSError with ValueError (Cygwin bugfix)

- tests/test_samples_create_tpmca
- tests/test_tpm2_save_load_state_2
test_samples_create_tpmca needs to wait longer for the pid file content
to be there not just until the file is available.
test_tpm2_save_load_state_2 needs to dump the TPM log file on failure.
Failures occurred rarely because the previous instance of swtpm had
not shut down yet and released the lock file while the new instance
wanted to lock the lockfile. So we have to wait a bit until the
previous instance is gone.
> tests: Wait a bit for pid file content; dump log on failure

- man/man8/swtpm_setup.pod
- src/swtpm_setup/py_swtpm_setup/swtpm_setup.py
- tests/Makefile.am
- tests/common
- tests/patches/0001-Deactivate-test-cases-accessing-rootcerts.txt.patch
- tests/patches/0002-Implement-powerup-for-swtpm.patch
- tests/patches/0003-Set-CRYPTOLIBRARY-to-openssl.patch
- tests/patches/0004-Store-volatile-state-at-every-step.patch
- tests/patches/0005-Disable-tests-related-to-events.patch
- tests/patches/0006-Disable-testing-with-RSA-3072.patch
- tests/patches/0007-Disable-rev155-test-cases.patch
- tests/patches/0008-Disable-x509-test-cases.patch
- tests/patches/0009-Disable-getcapability-TPM_CAP_ACT.patch
- tests/test_samples_create_tpmca
- tests/test_tpm2_ibmtss2
- tests/test_tpm2_samples_create_tpmca
- tests/test_tpm2_samples_swtpm_localca
- tests/test_tpm2_samples_swtpm_localca_pkcs11
- tests/test_tpm2_save_load_state_3
This PR
- adds a note to the usage of --allow-signing to swtpm_setup that usage of this option creates a non-standard EK
- Applies patches to the IBM TSS2 test suite in test_ibmtss2 and stores the volatile state at every stop on the way to ensure that the volatile state doesn't run into a pAssert as was the case with libtpms issue 195
- Consolidates the setting of CERTTOOL into common.sh
> Test cleanups and swtpm_setup clarification

- configure.ac
RHEL 7's gnutls 3.3.29 does not take the private key passwords like later
versions take it. We require at least 3.4.0, though I am not entirely sure
when that change occurred. We may actually require >3.4.0.
> build-sys: Check for minimum required gnutls 3.4.0

- configure.ac
- src/swtpm/Makefile.am
This allows user to set specific flags during compilation, without
overriding configure-time cflags necessary for compilation.
See also:
https://www.gnu.org/software/automake/manual/html_node/User-Variables.html
https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html
> build-sys: leave CFLAGS/LDFLAGS for user to be defined

- src/swtpm_cert/ek-cert.c
These types have been [renamed](https://gitlab.com/gnutls/libtasn1/-/commit/97f40453042a02371269f2d7af6f46928276ece8) in [libtasn1 version 3.0 (released 2012-10-28)](https://savannah.gnu.org/forum/forum.php?forum_id=7409). The most recent [libtasn1 version 4.17.0 (released 2021-05-13)](https://lists.gnu.org/archive/html/info-gnu/2021-05/msg00010.html) now [prints deprecation warnings](https://gitlab.com/gnutls/libtasn1/-/commit/fae39782b38e9e84705bf743d2cc827a1411f53a) that are made fatal by `-Werror`:
```
ek-cert.c:76:13: error: 'ASN1_ARRAY_TYPE' macro is deprecated, use 'asn1_static_node' instead. [-Werror]
76 | extern const ASN1_ARRAY_TYPE tpm_asn1_tab[];
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
```
The new types were introduced almost ten years ago, so they should be …
> swtpm_cert: rename deprecated libtasn1 types

- samples/py_swtpm_localca/swtpm_localca.py
Have the statedir created in case it doesn't exist before checking for read
and write access to it.
Set the default directory where to write the results into to the current
directory '.' rather than to what would result in the root directory.
> sample: swtpm-local: Fix a few minor issues

- configure.ac
- debian/changelog
- src/swtpm_setup/swtpm_setup_utils.c
- swtpm.spec
Cygwin's regex implementation doesn't seem to understande \\s
but needs [[:space:]] instead to properly skip over spaces.
> swtpm_setup: Replace '\\s' in regex with [[:space:]] to fix cygwin

- configure.ac
- dist/swtpm.spec
- src/swtpm_cert/ek-cert.c
These types have been renamed in libtasn1 version 3.0 (released 2012-10-28).
The most recent libtasn1 version 4.17.0 (released 2021-05-13) now prints
deprecation warnings that are made fatal by -Werror:
ek-cert.c:76:13: error: 'ASN1_ARRAY_TYPE' macro is deprecated, use 'asn1_static_node' instead. [-Werror]
76 | extern const ASN1_ARRAY_TYPE tpm_asn1_tab[];
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
The new types were introduced almost ten years ago, so they should be pretty
universally available by now.
Signed-off-by: Jonas Witschel <diabonas@archlinux.org>
> swtpm_cert: rename deprecated libtasn1 types 

- src/swtpm/swtpm_aes.c
- src/swtpm/swtpm_nvfile.c
Some of the code comes from libtpms, where various methods are named
"TPM_Something". The swtpm version of these methods are named
"SWTPM_Something". However, certain debug/log messages and comments were
updated accordingly to reflect that.
This is a cosmetic change that fixes that.
Signed-off-by: Felipe Franciosi <felipe@nutanix.com>
> swtpm: Fix SWTPM names in comments and messages

- tests/test_swtpm_setup_create_cert
- tests/test_tpm2_swtpm_setup_create_cert
Use the variables from tests/common for executables used in the
swtpm_setup_create_cert tests.
> tests: Use common vars for executables in swtpm_setup_create_cert tests

- src/swtpm_setup/swtpm.c
- src/swtpm_setup/swtpm_setup.c
Gerror was not initialized to NULL in one place. In the other it wasn't
freed.
> swtpm_setup: Initialize Gerror and free it

- configure.ac
- src/swtpm/Makefile.am
This PR fixes some issues related to the build system:
- Get rid of some obsolete macros
- Report $CFLAGS and $LDFLAGS at the end
- Remove AC_SUBST() for AM_CFLAGS and AM_LDFLAGS
- Remove using -L$(PWD)/.libs -lswtpm_libtpms on linking
For this PR I cherry-picked patches from  Tomasz Kłoczko <kloczek@github.com> (@kloczek)
> Fix some issues related to the build system

- configure.ac
autoreconf from autoconf 2.71 emmits a lot of warnings:
```
+ autoreconf -fiv
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal --force -I m4 …
```
> build-sys: Call autoupdate and fix some resulting issues

- tests/Makefile.am
The test test_tpm2_save_load_state seems to have been forgotten
about and was not run. Add it now to the the tests to run.
> tests: Add test_tpm2_save_load_state to the tests to run

- man/man8/Makefile.am
Add a missing '\' to the list of pod files and reduced the EXTRA_DIST
files to only those available from git.
> man8: Add missing '\' to list of pod files and reduced EXTRA_DIST files

- src/swtpm_setup/swtpm.c
Since commit 502cb1129ad59 -D_FORTIFY_SOURCE=2 is passed to the gcc
command line resulting in memcpy() becoming a macro on Cygwin, which
then causes the following compiler errors due to the anonymous arrays
being used:
swtpm.c: In function ‘swtpm_tpm2_createprimary_ek_rsa’:
swtpm.c:686:26: error: macro "memcpy" passed 34 arguments, but takes just 3
686 |         }, authpolicy_len);
|                          ^
In file included from /usr/include/string.h:180,
from swtpm.c:15:
/usr/include/ssp/string.h:97: note: macro "memcpy" defined here
97 | #define memcpy(dst, src, len) __ssp_bos_check3(memcpy, dst, src, len)
|
swtpm.c:682:9: error: statement with no effect [-Werror=unused-value]
682 |         memcpy(authpolicy, (unsigned char []){
|         ^~~~~~
swtpm.c:698:26: error: macro "memcpy" …
> swtpm_setup: Fix compiler errors when memcpy is a macro (Cygwin)

- .gitignore
- configure.ac
- samples/Makefile.am
- samples/swtpm-localca.2inst.in
Use a different script for local testing that what is installed into
/usr/share/swtpm/swtpm-localca.
> samples: Use different script for local testing than install

- .gitignore
- Add auto-generated files `debian/autoreconf.*`
- Remove `*.patch` (Quilt requires these under `debian/patches/`)
Avoids the following untracked files after a build:
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
debian/autoreconf.after
debian/autoreconf.before
```
> Improvements to .gitignore

- man/man8/swtpm-create-tpmca.pod
Fixes [bad-whatis-entry](https://lintian.debian.org/tags/bad-whatis-entry) Lintian warning.
> Add missing title to swtpm-create-tpmca(8) manual page

- man/man8/swtpm_setup.pod
`swtpm_setup.sh(8)` was replaced by `swtpm_setup(8)` in v0.5.0.
> Correct old reference to swtpm_setup.sh in manpage

- .gitignore
Since this file is [meant to be versioned](https://github.com/stefanberger/swtpm/pull/496#issuecomment-884432135), it should not be in `.gitignore`.
> Remove swtpm.spec from .gitignore

- debian/clean
- debian/control
- debian/not-installed
- debian/rules
- debian/swtpm-dev.install
- debian/swtpm-libs.install
- debian/swtpm-tools.install
- debian/swtpm-tools.postinst.in
- debian/swtpm.install
- `debian/clean`: Add files that were not being automatically cleaned up by `dh(1)`'s `clean` target.
- `debian/control`:
- Add new recommended/required fields and bump `Standards-Version`.
- Remove redundant build dependencies that are implied transitively.
- Bump `debhelper` dependency version to match `debian/compat`.
- Move `swtpm-libs`'s `${misc:Pre-Depends}` dependency to `Pre-Depends`. Resolves `depends-on-misc-pre-depends` Lintian warning.
- Sort packages and dependency lists alphabetically as per `wrap-and-sort(1)`.
- `debian/not-installed`: List deliberately non-installed files to avoid `dh_missing(1)` warnings.
- `debian/rules`:
- Pass `--no-scripts` to `dh_makeshlibs(1)` in order to keep an `ldconfig(8)` trigger from being implicitly added, which for this package was redundant …
> Debian packaging improvements

- configure.ac
- src/swtpm/Makefile.am
- src/swtpm_bios/Makefile.am
- src/swtpm_cert/Makefile.am
- src/swtpm_ioctl/Makefile.am
- src/swtpm_localca/Makefile.am
- src/swtpm_setup/Makefile.am
- src/utils/Makefile.am
This PR enables us to pass CFLAGS and LDFLAGS during configure time. It then also allows us to pass CFLAGS and LDFLAGS (was working already) again during build-time as additional flags like this (using eye-catchers):
configure time:
```
CFLAGS="-Werror -Werror -Werror -Werror" LDFLAGS="-lc -lc -lc -lc" ./configure --prefix=/usr
```
build time:
```
make V=1 CFLAGS="-Wextra -Wextra -Wextra -Wextra" LDFLAGS="-lm -lgnutls-dane" 2>&1 | tee make.log
```
> Allow passing CFLAG and LDFLAGS during configure and build time

- .gitignore
- debian/rules
- debian/swtpm-tools.install
- man/man8/Makefile.am
- man/man8/swtpm-create-tpmca.pod
- man/man8/swtpm-localca.8
- man/man8/swtpm-localca.conf.pod
- man/man8/swtpm-localca.options.pod
- man/man8/swtpm_localca.pod
- man/man8/swtpm_setup.pod
- swtpm.spec
- swtpm.spec.in
This pulls request implements **option 1.a** proposed in [this discussion](https://github.com/stefanberger/swtpm/issues/499#issuecomment-885984150) and resolves the [no-manual-page Lintian warning](https://lintian.debian.org/tags/no-manual-page) that's currently being triggered by `swtpm_localca` being installed without a matching manual page.
- Rename `swtpm-localca(8)` manual page to `swtpm_localca(8)` and make `swtpm-localca(8)` an alias for `swtpm_localca(8)`, mirroring the fact that `/usr/bin/swtpm_localca` is the actual program and `/usr/share/swtpm/swtpm-localca` a wrapper for it.
- Change references to `swtpm-localca` in manual pages' content to `swtpm_localca`, reflecting the actual name of the program they are meant to document.
⚠️ **Either** this **or** #506 should be merged; …
> Change swtpm-localca to swtpm_localca in manpages

- man/man8/swtpm_setup.pod
- src/swtpm_setup/swtpm.c
- src/swtpm_setup/swtpm.h
- src/swtpm_setup/swtpm_setup.c
- src/utils/swtpm_utils.c
- src/utils/swtpm_utils.h
- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
- tests/test_swtpm_setup_create_cert
- tests/test_tpm2_swtpm_setup_create_cert
This PR implements an option for swptm_setup to write the created EK certificates into a directory. It addresses issue #455.
> swtpm_setup: Write EK certificate files into a directory

- src/swtpm/ctrlchannel.c
The code that handles control channel command `CMD_SET_DATAFD`, introduced in [this commit](https://github.com/stefanberger/swtpm/commit/1fb8bb790f5bd7d81a97be7507d1063aa3bb2c58), overwrites `mlp->flags` instead of `OR`ing new bits onto it. This causes any flags previously set by the command-line argument parsers (in `swtpm::swtpm_main()` and `swtpm_chardev::swtpm_chardev_main()`) to be lost.
> swtpm: Preserve main loop flags when handling CMD_SET_DATAFD

- man/man8/swtpm_setup.pod
- src/swtpm_setup/swtpm_setup.c
- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
Implement get_supported_tpm_versions to get swtpm's support for TPM 1.2
and TPM 2 and use it error out in case user choose a TPM version that
is not supported. Also display the supported TPM versions in the
capabilites JSON.
> swtpm_setup: Add support for checking for TPM 1.2 and TPM 2 support     

- src/swtpm/common.c
This change is conforming to the following SEI CERT recommendation.
MEM03-C. Clear sensitive information stored in reusable resources:
https://wiki.sei.cmu.edu/confluence/display/c/MEM03-C.+Clear+sensitive+information+stored+in+reusable+resources
> swtpm: Wipe out key to ensure it is not left on the stack

- src/swtpm/seccomp_profile.c
glib's (v2.68) g_thread_pool_new() calls the syscall sched_setattr(),
which we must allow to avoid termination of the CUSE TPM.
This patch resolves issue #520.
> swtpm: Allow sched_setattr in seccomp profile for CUSE TPM

- src/swtpm/swtpm_nvstore_dir.c
Fix the following compilation issue:
swtpm_nvstore_dir.c: In function 'SWTPM_NVRAM_Validate_Dir':
swtpm_nvstore_dir.c:149:86: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
TPM_DEBUG("SWTPM_NVRAM_Validate_Dir: Rooted state path %s\n", tpm_state_path);
^
> swtpm: Add missing braces around TPM_DEBUG after if statement

- tests/Makefile.am
- tests/common
- tests/test_ctrlchannel2
- tests/test_ctrlchannel4
- tests/test_tpm2_ctrlchannel2
Skip tests that require the chardev after checking for the chardev
interface support in swtpm. Remove the conditional addition of chardev
related tests from the Makefile.am.
> tests: Skip chardev related tests after checking for chardev support

- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/swtpm_nvstore.c
- src/swtpm/swtpm_nvstore.h
- src/swtpm/swtpm_nvstore_dir.c
- src/swtpm_setup/swtpm_setup.c
- tests/Makefile.am
- tests/_test_print_states
- tests/_test_tpm2_print_states
- tests/test_print_states
- tests/test_swtpm_setup_overwrite
- tests/test_tpm2_print_states
- tests/test_tpm2_swtpm_setup_overwrite
Currently, swtpm_setup checks TPM state existence by directly accessing TPM state dir. To support pluggable storage backend https://github.com/stefanberger/swtpm/issues/461 , it's better for swtpm_setup not to have dependencies on implementation details of TPM state backend.
This PR introduces a new option "--print-states" to swtpm. With this option, swtpm shows TPM state status as follows:
```
$ swtpm socket --print-states --tpmstate dir=/tmp --tpm2 | jq .
{
"type": "swtpm",
"states": [
{
"name": "tpm2-00.permall"
}
]
}
```
Through that output, swtpm_setup can check existence of TPM state.
Current "--print-states" only shows "permall" state as it's the only one currently required for swtpm_setup. Of course it's open to discuss whether we should have other names ("volatile", "savestate"). …
> Introduce "--print-states" to check TPM state existence

- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/swtpm_nvstore.c
- src/swtpm/swtpm_nvstore.h
- tests/test_tpm2_print_states
Some minor fixes for `--print-states` which is recently introduced in https://github.com/stefanberger/swtpm/pull/524. This PR includes function name change (Print_Json => PrintJson), a test fix and error handling fix.
> Minor fixes for --print-states option

- configure.ac
To be able to build with OpenSSL 3.0 we need to added
-Wno-deprecated-declarations to the default CFLAGS.
> build-sys: Add -Wno-deprecated-declarations to default CFLAGS (OSSL 3)

- tests/_test_tpm2_save_load_state_da_timeout
When there is a delay between "Sending TPM2_NV_Write with wrong
password" and "timenow=$(date +%s)", the test can fail with "Error: Did
not get expected failure from TPM2_NV_Write() with good password.
Lockout should be enabled.". This can sometimes happen on slow or busy
systems.
To stabilize the test, this patch introduces precise recovery time
measurement ($timerecovery) and check good password works after that
time. As for lockout timeout, moves starting timer just before
TPM2_NV_Write and check good password fails before that time.
> tests: Fix test_tpm2_save_load_state_da_timeout rare timer race

- configure.ac
- src/swtpm/Makefile.am
Use the (undocumented) OPENSSL_SUPPRESS_DEPRECATED to suppress the
deprecated API warnings when compiling swtpm and swtpm_setup with
OpenSSL 3.0.0 replacing the global -Wno-deprecated-declarations.
> build-sys: Use -DOPENSSL_SUPPRESS_DEPRECATED (OSSL 3)

- src/selinux/Makefile.am
> build-sys: selinux: Compare absolute path against absolute path

- configure.ac
- src/swtpm/Makefile.am
- src/swtpm/swtpm_aes.c
Use the EVP_CIPHER implementation for the AES CBC computations. This
API has been supported already in OpenSSL 1.1.x for sure and is also
not deprecated in OpenSSL 3.0.
This partially resolves issue #538.
> swtpm: Use EVP_CIPHER in SWTPM_SymmetricKeyData_Encrypt/Decrypt

- src/swtpm/ctrlchannel.c
We recently agreed in [this conversation](https://github.com/stefanberger/swtpm/pull/509#issuecomment-890412478) that the `CMD_SET_DATAFD` handler shouldn't be setting `MAIN_LOOP_FLAG_END_ON_HUP` because:
- `MAIN_LOOP_FLAG_END_ON_HUP` is causing `swtpm` to _unconditionally_ terminate when the data channel connection drops,
- the `--terminate` command-line switch—which is supposed to allow the user to control this behavior—isn't being respected,
- the `CMD_SET_DATAFD` handler should stick to doing what it's meant to do (i.e. set the data channel FD) and nothing more, and
- consumers who want the daemon to self-terminate upon data channel HUP should simply use the `--terminate` switch, which has existed from the very beginning and is _the_ proper, documented, and officially supported way of …
> swtpm: Don't set MAIN_LOOP_FLAG_END_ON_HUP flag in CMD_SET_DATAFD handler

- src/swtpm_ioctl/tpm_ioctl.c
If is_chardev is false, then we have a buffersize of 4096 bytes per
the following statement:
322    if (!is_chardev)
323        buffersize = 4096;
With this we end up in the following if branch:
384        if (buffersize) {
385            /* continue with the read interface */
[...]
418
419            break;
420        } else {
Per the break in line 419 we leave the loop, thus cannot reach the
statement we remove:
423        if (!is_chardev)
424            break;
> swptm_ioctl: Eliminate an unreachable statement

- src/swtpm/swtpm_nvstore.c
- src/swtpm/swtpm_nvstore.h
- src/swtpm/swtpm_nvstore_dir.c
- src/swtpm/swtpm_nvstore_dir.h
Cleanup on the storage backend side on shutdown to unlock the
locked directory.
> swtpm: Cleanup storage backend on shutdown to unlock dir

- src/swtpm/swtpm_nvstore.c
- src/swtpm_setup/swtpm_setup.c
- tests/_test_print_states
- tests/_test_tpm2_print_states
Search for all the state files not just the permanent state and
when printing the JSON use the abstracted names rather than concrete
filenames that are only valid for the dir backend but will likely
not exist in other backends.
Adjust swtpm_setup to search for the abstracted name and also
adjust the error message to print out the abstracted name.
Adjust the test cases.
> swtpm: Search for all state files and use abstracted names in JSON

- src/swtpm/swtpm_nvstore.c
- src/swtpm/swtpm_nvstore.h
- src/swtpm/swtpm_nvstore_dir.c
- tests/_test_print_states
- tests/_test_tpm2_print_states
Add the size of the type state to the --print-states output and switch
back to a JSON object when enumerating the blobs.
> swtpm: Add size to each type of state and use JSON object

- src/swtpm_setup/swtpm_setup.c
- tests/Makefile.am
- tests/_test_tpm2_file_permissions
- tests/common
- tests/test_tpm2_file_permissions
Add a test case for testing the --runas parameter and the ability to access
existing files that have restrictive access permission so that only allow
the --runas user is able to access these files. This is to ensure that
swtpm can access these files properly when the handling of options and the
changing to the --runas user is moved around within swtpm.
> Tests: Add a test case for testing --runas and ability to access files

- tests/_test_tpm2_file_permissions
BSD cp does not understand the -d option, so remove it.
It's better to use "su -u nobody -c '...'" than sudo, which makes
this test also work on the BSDs.
> test: Fix test_tpm2_file_permissions for BSD

- configure.ac
- src/swtpm_setup/swtpm_setup.c
- swtpm.spec
Backport a patch for swtpm_setup.
> swtpm_setup: Fix exit code on error to be '1'. 

- configure.ac
This enables address and undefined sanitizers.
> build-sys: Introduce --enable-sanitizers to configure

- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm_setup/swtpm.c
- src/swtpm_setup/swtpm_setup.c
Whenever swtpm_setup is executed with --logfile option, forward the option to swtpm (--log file=...). This helps debugging swtpm initialization issues.
> swtpm_setup: Forward --logfile option to swtpm

- src/swtpm_localca/swtpm_localca.c
- tests/_test_tpm2_print_capabilities
- tests/common
This PR fixes a memory leak in swtpm_setup and some issues related to tests.
> Fix memory leak in swtpm_setup and some issues with tests

- src/swtpm_localca/swtpm_localca.c
- src/swtpm_setup/swtpm_setup.c
This PR fixes more memory leaks that were detected with --enable-sanitizers and that can be easier detected with gcc.
> Fix more memory leaks detected with --enable-sanitizers

- src/swtpm_setup/swtpm_setup.c
FreeBSD returns errno EINVAL rather than ENOENT once there are not more
entries in a directory to walk over.
> swtpm_setup: Fix errno comparison on end-of-directory (FreeBSD)

- src/swtpm/swtpm_nvstore_dir.c
Only recent libvirt versions have the patch for the AppArmor profile for
libvirt to allow fsync after opening a directory. Rather than failing
hard on this error, log it once and continue and do not try fsync again
after.
This patch addresses the problems seen on Ubuntu related to an older
version of libvirt without the AppArmor profile update.
- issue #484
- issue #549
- issue #559
> swtpm: Make fsync() errors non-fatal (for libvirt using AppArmor) 

- tests/test_tpm2_swtpm_localca_pkcs11.test
The key is freed using 'gnutls_privkey_deinit(pkcs11key)', yet the
following memory leaks show up that are most likely in the pkcs11 module.
Skip the test if ASAN is being used to avoid the test failure.
Direct leak of 55080 byte(s) in 1 object(s) allocated from:
#0 0x7fdabb152af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
#1 0x7fdab6b737c6 in C_Initialize (/usr/lib64/pkcs11/libtpm2_pkcs11.so+0x147c6)
#2 0x7fdab9a5f8a9 in initialize_module_inlock_reentrant (/lib64/libp11-kit.so.0+0x2b8a9)
#3 0x7fdab9a5fc88 in managed_C_Initialize (/lib64/libp11-kit.so.0+0x2bc88)
#4 0x7fdab9a66018 in p11_kit_modules_initialize (/lib64/libp11-kit.so.0+0x32018)
#5 0x7fdab9a66778 in p11_kit_modules_load_and_initialize (/lib64/libp11-kit.so.0+0x32778)
#6 0x7fdabab10dc5 in auto_load …
> tests: Skip TPM 2 pkcs11-related test when ASAN is used

- man/man8/swtpm.pod
- src/swtpm/Makefile.am
- src/swtpm/capabilities.c
- src/swtpm/common.c
- src/swtpm/swtpm_nvstore.c
- src/swtpm/swtpm_nvstore.h
- src/swtpm/swtpm_nvstore_linear.c
- src/swtpm/swtpm_nvstore_linear.h
- src/swtpm/swtpm_nvstore_linear_file.c
- src/swtpm/utils.h
- tests/Makefile.am
- tests/_test_print_capabilities
- tests/_test_save_load_state
- tests/_test_tpm2_print_capabilities
- tests/test_save_load_state
- tests/test_tpm2_save_load_state_2
- tests/test_tpm2_save_load_state_2_block
- tests/test_tpm2_save_load_state_2_linear
This RFC is based on the work of @Etsukata et. al. in #461 and #490. It uses the proposed abstraction layer to implement another nvram storage backend.
The backend is called "linear" (which, IMO, is a not a good name [for the user facing side anyway], "file" would have been much better... but is already used by, well, the "file" directory backend - maybe we should call that one "directory" on the commandline?). It provides a second, lighter abstraction layer weakly based on the design proposed in #461 - the "linear" backend itself maps files into a linear address space, a "linear backend" is then used to write those changes to wherever they need to go.
One such "linear backend" is the "linear file" one implemented together with the abstraction in the first patch. It simply mmaps a file or …
> swtpm: add "linear" nvram store backend (for single-file storage and block devices)

- src/swtpm/swtpm_nvstore_linear_file.c
Cygwin internally uses the Windows API call FlushViewOfFile that
seems to not like to be called with an excessive number of bytes.
Instead, call it with length = 0 so that 'the file is flushed from
the base address to the end of the mapping' and then msync() succeeds.
Source:
https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-flushviewoffile
> swtpm: Call msync with length = 0 on Cygwin

- Makefile.am
- configure.ac
- man/man8/swtpm_setup.conf.pod
- man/man8/swtpm_setup.pod
- samples/swtpm_setup.conf.in
- scripts/Makefile.am
- scripts/test_pcr_bank_list
- src/swtpm_setup/swtpm_setup.c
- src/swtpm_setup/swtpm_setup_conf.h.in
- src/swtpm_setup/swtpm_setup_utils.c
This PR extends the configure script with a --enable-default-pcr-banks option to allow setting the default PCR banks to activate. By default the sha256 bank is now activated. Also allow the configuration of the default PCR bank via the swtpm_setup.conf configuration file's active_pcr_banks entry, which is used if the user didn't pass a choice via the command line. If nothing is found in swtpm_setup.conf then fall back to what was chosen when configure was run.
> Allow customization of default PCR banks using configure option and swtpm_setup.conf

- src/swtpm_localca/swtpm_localca.c
- src/swtpm_localca/swtpm_localca_utils.c
- src/swtpm_localca/swtpm_localca_utils.h
Certain characters are not accepted by gnutls when creating the
subject with the 'CN' from the vmid, so we have to replace those
characters with another one, such as '_'.
> swtpm_localca: Replace certain characters in VMId's

- man/man8/swtpm_setup.pod
- src/swtpm_setup/swtpm_setup.c
- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
- tests/common
- tests/test_tpm2_swtpm_setup_create_cert
Add a --reconfigure option to swtpm_setup so that an existing state can be reconfigured
with a new set of active PCR banks.
> Add support for --reconfigure for swtpm_setup to reconfigure the active PCR banks

- tests/test_tpm12
- tests/test_tpm2_ibmtss2
Add CFLAGS="-DOPENSSL_SUPPRESS_DEPRECATED=1" to the configure line
to avoid compile-time errors when building the TPM 1.2 test with
OpenSSL 3.0.
IBM TSS2 v1.6 test does not currently work with OpenSSL 3.0, so
skip it.
> tests: OSSL 3: Make TPM 1.2 test compile; skip IBM TSS 2 test

- src/swtpm/swtpm_nvstore_linear_file.c
- tests/test_swtpm_setup_create_cert
Fix the following compilation error occurring on 32bit machines:
swtpm_nvstore_linear_file.c: In function 'SWTPM_NVRAM_LinearFile_Mmap':
swtpm_nvstore_linear_file.c:58:20: error: comparison of integer expressions of different signedness: '__off_t' {aka 'long int'} and 'unsigned int' [-Werror=sign-compare]
58 |     if (st.st_size >= (uint32_t)sizeof(struct nvram_linear_hdr)) {
|                    ^~
> swtpm: Fix compilation error on 32bit machines

- Makefile.am
- configure.ac
- scripts/Makefile.am
- scripts/test_pcr_bank_list
Move the regex test for the PCR banks into the configure script.
> build-sys: Move regex to test PCR banks into configure script

- configure.ac
- debian/changelog
- swtpm.spec
> build-sys: Bump up version to 0.8.0 at beginning of dev cycle

- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/tpmlib.c
- src/swtpm/tpmlib.h
Implement tpmlib_choose_tpm_version() that reports an error when an un-
supported version is chosen. Have it used by existing code where possible.
If TPM 1.2 is not supported by libtpms, the following message is now
displayed:
swtpm: Error: TPM 1.2 is not supported by libtpms.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2024583
> swtpm: Implement function reporting error when choosing unsupported TPM

- src/swtpm/swtpm_nvstore.c
This fix addresses Coverity issue CID 375869.
Check the header size indicated in the header of the state against the
expected size and return an error code in case the header size indicator
is different. There was only one header size so far since blobheader was
introduced, so we don't need to deal with different sizes.
Without this fix a specially craft header could have cause out-of-bounds
accesses on the byte array containing the swtpm's state.
> swtpm: Check header size indicator against expected size (CID 375869)

- .travis.yml
It's not possible to recreate the issue with the failing test case
locally on Xenial, so just disable the ASAN usage on swtpm by disabling
the CFLAGS variable.
The one failing test case show this. All other ones work.
FAIL: test_parameters
=====================
Test 0: SUCCESS with parameters ''.
Test 1: SUCCESS with parameters '--createek'.
Test 2: ==27310==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
ERROR: Test with parameters '--take-ownership' failed.
FAIL test_parameters (exit status: 1)
> Travis: Stop using ASAN for swtpm since one test case fails

- src/swtpm_localca/swtpm_localca.c
Avoid trying to create TPM certificates while the issuer certificate has not
been created, yet (in a 2nd step).
To resolve this do not just test for availability of the signing key, which
is created first, but also test for the issuer certifcate, which is created
in a 2nd step when the local CA is created. If either one is missing,
attempt to create the CA.
Resolves: https://github.com/stefanberger/swtpm/issues/644
> swtpm_localca: Test for available issuercert before creating CA

- configure.ac
Add probing for -fstack-protector to the existing
-fstack-protector-strong since not all platforms support either one
of them.
> build-sys: Add probing for -fstack-protector

- src/swtpm/daemonize.c
With relative paths being used the chdir("/") in daemonize_finish() will
cause file access errors.
Fixes: 98d1d12 ("swtpm: Make --daemon not racy")
Resolves: https://github.com/stefanberger/swtpm/issues/671
> swtpm: Do not chdir(/) when using --daemon

- src/swtpm_bios/tpm_bios.c
- src/swtpm_ioctl/tpm_ioctl.c
This PR fixes swtpm_ioctl and swtpm_bios so that for the tcp_port number parsing an unsigned int is being used so that negative port numbers can be reported back to the user as an error.
> Use unsigned int for tcp port number parsing to avoid negative port numbers being used

- src/swtpm/tlv.c
To avoid an integer wrap-around use uint64_t for 'offset' so that adding
an untrusted 32-bit number will allow for comparison against the trusted
'buffer_len' 32-bit number:
if (offset + td->tlv.length > buffer_len)
return NULL;
This avoids possible out-of-bound accesses and crashes when reading
specially crafted input data that have a tlv.length causing an integer
overflow.
> swtpm: Use uint64_t to avoid integer wrap-around when adding a uint32_t

- configure.ac
- include/swtpm/tpm_ioctl.h
- src/swtpm_ioctl/tpm_ioctl.c
gcc 12.1 supports _FORTIFY_SOURCE=3. Modify the existing check for whether
_FORTIFY_SOURCE=2 can be used to test compile with the user provided
CFLAGS and only add _D_FORTIFY_SOURCE=2 to the HARDENING_CFLAGS if the
user doesn't provide anything that's not compatible.
Following an online article _FORTIFY_SOURCE=3 may add more overhead, so
we only go up to level 2 for now and let build servers or user provide
the higher level via the CFLAGS.
https://developers.redhat.com/blog/2021/04/16/broadening-compiler-checks-for-buffer-overflows-in-_fortify_source#what_s_next_for__fortify_source
Resolves: https://github.com/stefanberger/swtpm/issues/688
> build-sys: Fix configure script to support _FORTIFY_SOURCE=3

- configure.ac
- include/swtpm/tpm_ioctl.h
- src/swtpm_ioctl/tpm_ioctl.c
This PR backports a patch for gcc 12.1 to support _FRTIFY_SOURCE=3 and a patch for Cygwin that fixes a test-compile issue.
> Backport patch to support gcc 12.1 and _FORTIFY_SOURCE=3

- tests/patches/0001-Deactivate-test-cases-accessing-rootcerts.txt.patch
- tests/patches/0010-Adjust-test-cases-for-OpenSSL-3.patch
- tests/test_tpm2_ibmtss2
Apply a patch to the IBM TSS2 v1.6 test suite when OpenSSL 3.x is de-
tected.
> tests: Patch IBM TSS2 test suite for OpenSSL 3.x

- debian/control
- debian/rules
- debian/swtpm.install
- debian/usr.bin.swtpm
Hello Stefan,
As a part of the inclusion of swtpm into Ubuntu Jammy Jellyfish I created an apparmor profile to limit unnecessary permissions. This pull request contains the profile and its changes from versions [0.6.1-0ubuntu6](https://launchpad.net/ubuntu/+source/swtpm/0.6.1-0ubuntu6), [0.6.3-0ubuntu1](https://launchpad.net/ubuntu/+source/swtpm/0.6.3-0ubuntu1), and [0.6.3-0ubuntu3](https://launchpad.net/ubuntu/+source/swtpm/0.6.3-0ubuntu3). I also created a [ppa](https://launchpad.net/~lvoytek/+archive/ubuntu/swtpm-upstream-apparmor-profile) for testing the profile alongside your current development release 0.8.0~dev1 in Jammy.
Thanks
> debian: Add swtpm apparmor profile upstream from Ubuntu

- src/swtpm/swtpm_nvstore_dir.c
Commit https://github.com/stefanberger/swtpm/commit/2d3deaef291e045a2188287d18d42f2dd58173bf forgot to move the check for whether the lock file has
already been opened into the new function opening the lock file and there-
fore the lock file is now opened whenever swtpm gets a PTM_INIT. This fix
prevents the reopening of the lockfile if it has already been opened.
Otherwise many PTM_INIT's will lead to failure since no more files can
be opened.
> swtpm: Avoid locking directory multiple times

- src/swtpm_bios/tpm_bios.c
- src/swtpm_bios/tpm_bios.h
- tests/test_tpm2_swtpm_setup_create_cert
Use SHA-256 in swtpm_bios when sending TPM2_IncrementalSefTest() rather than SHA-1.
Do not use the SHA-1 PCR bank in swtpm_setup test cases but the SHA-256 bank instead.
> Use SHA-256 rather than SHA-1 in swtpm_bios and test case

- configure.ac
- src/swtpm/Makefile.am
- src/swtpm/cuse_tpm.c
- src/swtpm/fips.c
- src/swtpm/fips.h
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
While libtpms does not provide any means to disable FIPS-disabled crypto
algorithms from being used, work around the issue by simply disabling the
FIPS mode of OpenSSL if it is enabled. If it cannot be disabled, exit
swtpm with a failure message that it cannot be disabled. If FIPS mode
was successfully disabled, print out a message as well.
> swtpm: Disable OpenSSL FIPS mode to avoid libtpms failures

- configure.ac
PCR Bank verification needs bash, so check for bash. While at it use the
autoconf shell construct macros over raw shell syntax which is slightly
more portable.
Examples:
./configure --enable-default-pcr-banks=sha256,sha920
checking which PCR banks to activate by default... configure: error: sha256,sha920 is an invalid list of PCR banks
./configure --enable-default-pcr-banks=sha256,sha512
checking which PCR banks to activate by default... sha256,sha512
./configure
checking which PCR banks to activate by default... sha256
Signed-off-by: William Roberts <william.c.roberts@intel.com>
> configure: check for bash

- src/swtpm/capabilities.c
- src/swtpm/capabilities.h
- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
All callers to capabilities_print_json() call TPMLIB_ChooseTPMVersion
right before. Move it into the function now and check the return
code.
> swtpm: Move TPMLIB_ChooseTPMVersion into capabilities_print_json

- src/swtpm/capabilities.c
Revert the change from the previous patch that shows an error when
TPMLIB_ChooseTPMVersion fails but rather ignore the error as before.
If a TPM 2 is supported then tpm-2.0 capability verb will be shown
and if a TPM 1.2 is supported then tpm-1.2 will be shown, thus
allowing someone reading the JSON to determine what is supported.
> swtpm: Ignore error if TPMLIB_ChooseTPMVersion for printing caps fails

- src/swtpm/seccomp_profile.c
Add some more recent syscalls to the disallowlist in the seccomp
profile.
> swtpm: Add some more recent syscalls to seccomp profile

- src/swtpm/seccomp_profile.c
I think there was a small typo with the seccomp profile creation.
The project wouldn't compile on my ubuntu 20.04.1 based system with the error message:
```
CC       libswtpm_libtpms_la-seccomp_profile.lo
In file included from seccomp_profile.c:44:
seccomp_profile.c: In function ‘create_seccomp_profile’:
seccomp_profile.c:105:9: error: ‘__SNR_fs_mount’ undeclared (first use in this function)
105 |         SCMP_SYS(fs_mount),
|         ^~~~~~~~
seccomp_profile.c:105:9: note: each undeclared identifier is reported only once for each function it appears in
```
My guess is that this is simply a typo and `fs_mount` was supposed to be `fsmount`.
**Note:** I have no previous expertise with seccomp, so please double check. Maybe `fs_mount` is a valid name that is just not available on my …
> Fixed typo `fs_mount` vs `fsmount`

- src/swtpm/cuse_tpm.c
- src/swtpm/fips.c
- src/swtpm/fips.h
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/tpmlib.c
- src/swtpm/utils.h
This PR renames `disable_fips_mode()` to `fips_mode_disable()` and moves it into `tpmlib_start()` after `TPMLIB_MainInit()` to consolidate the call in a single place. Refactor the code to create the new function `fips_mode_enabled()`.
> Refactor FIPS related code

- src/swtpm/seccomp_profile.c
If seccomp-syscalls.h lags behind the syscall definition of __NR_xyz then
the __SNR_xyz #define is not available. Therefore, switch to check for
__SNR_xyz #define because they are available if __NR_xyz is available.
> swtpm: seccomp: Check for __SNR_xyz rather than __NR_xyz

- src/swtpm_ioctl/tpm_ioctl.c
> swtpm_ioctl: Only close file descriptor if >= 0 (Coverity)

- man/man8/swtpm.pod
- src/swtpm/capabilities.c
- src/swtpm/common.c
- src/swtpm/common.h
- src/swtpm/ctrlchannel.c
- src/swtpm/cuse_tpm.c
- src/swtpm/mainloop.c
- src/swtpm/mainloop.h
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/tpmlib.c
- src/swtpm/tpmlib.h
- tests/Makefile.am
- tests/_test_print_capabilities
- tests/_test_tpm2_avoid_da_lockout
- tests/_test_tpm2_print_capabilities
- tests/test_tpm2_avoid_da_lockout
If necessary send a TPM2_Shutdown() command to libtpms before processing
CMD_INIT. However, this is only necessary for a TPM 2 and only if the
TPM2_Shutdown command has not been sent by the client (VM TPM driver) as
the last command as it should do under normal circumstances, for example
upon graceful VM shutdown.
This fixes a bug where abrupt VM resets may trigger the TPM 2's dictionary
attack lockout logic due to the TPM 2 not having received a TPM2_Shutdown
command before it was reset using CMD_INIT for example. An OS driver is
typically supposed to send a TPM2_Shutdown to the TPM 2 but an abrupt VM
reset prevents it.
There are 3 control commands where this needs to be done since they
call TPMLIB_Terminate():
- CMD_STOP:
This command is typically called before setting the state blobs …
> Send a TPM2_Shutdown before TPMLIB_Terminate() in case client did not send it

- src/swtpm_setup/swtpm_setup.c
> swtpm_setup: Add missing description for --vmid to help screen

- man/man8/swtpm.pod
- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/utils.c
- src/swtpm/utils.h
- tests/Makefile.am
- tests/test_tpm2_chroot_chardev
- tests/test_tpm2_chroot_cuse
- tests/test_tpm2_chroot_socket
Add an option to enter a chroot after starting swtpm. This is useful for
sandboxing purposes. When this option is used, it is expected that swtpm
is started as root and the --runas option is used to subsequently drop
privileges (otherwise the chroot could be escaped).
Signed-off-by: Jennifer Herbert <jennifer.herbert@citrix.com>
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
> swtpm: Add a chroot option

- src/swtpm/fips.c
On OpenBSD openssl/fips.h is not available and FIPS_mode() is not
available, so implement a stub for fips_mode_enabled().
> swtpm: Implement stub for fips_mode_enabled (OpenBSD)

- include/swtpm/tpm_ioctl.h
QEMU has made a change to a copy of this header file with the following
reason:
On Solaris and Haiku, the _IO() macros are defined in <sys/ioccom.h>.
Add a proper check for this header to our build system, and make sure
to include the header in tpm_ioctl.h to fix a build failure on Solaris
and Haiku.
> headers: Synchronize with header in QEMU project

- tests/test_tpm2_save_load_state_2_block
Older versions of fallocate do not support the --posix option that the test
needs. If --posix is not supported, skip the test.
Also check for availability of the losetup tool.
> tests: Check for fallocate tool and its support for --posix

- include/swtpm/tpm_ioctl.h
Apply recent changes to this file from upstream QEMU project using
a few #ifndef _WIN32 to make code compileable on Windows.
> headers: Apply #ifndef's for _WIN32 from QEMU project

- debian/clean
swtpm_cuse.8 is not generated anymore but its a static file now that must not be removed anymore via the debian/clean file.
Resolves: https://github.com/stefanberger/swtpm/issues/751
> debian: Do not remove swtpm_cuse.8 via clean file

- src/swtpm/cuse_tpm.c
- src/swtpm/mainloop.h
Increase the number of locking retries to 300 over 3 seconds instead of 100 over 1 second. This gives the failing side more time to release the lock.
> swtpm: Do 300 locking retries instead of only 100

- src/swtpm/ctrlchannel.c
- src/swtpm/cuse_tpm.c
- src/swtpm/mainloop.c
- src/swtpm/tpmlib.c
Also send TPM2_Shutdown when swtpm is terminated by a signal or due to
lost connection. Previously supported reasons for sending the TPM2_Shutdown
were primarily related to commands sent via the command channel.
> swtpm: Also send TPM2_Shutdown when swtpm terminates by signal 

- man/man8/swtpm.pod
- src/swtpm/capabilities.c
- src/swtpm/common.c
- src/swtpm/common.h
- src/swtpm/mainloop.c
- src/swtpm/mainloop.h
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- tests/Makefile.am
- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
- tests/test_ctrlchannel3
- tests/test_setdatafd.py
- tests/test_tpm2_ctrlchannel3
This PR adds support to swtpm upon loss of the control channel connection.
A swtpm command line may now look like this to enable automatic shutdown upon 
data channel connection loss (stream sockets, e.g. TCP) and Unix control channel:
```
swtpm socket \
--tpmstate dir=/tmp/mytpm1
--ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock,terminate \
--terminate \
--tpm2 \
--flags not-need-init
```
> swtpm: Add support for termination of swtpm upon control channel connection loss

- src/swtpm/swtpm_nvstore.c
Return TPM_FAIL if SWTPM_NVRAM_DecryptData() is called without a key or if an unhandle type of encryption mode is encountered. Previously this function would return no error but also would not do any decryption if no key was provided. Consequently, it would then also not return a byte array with decrypted data which in turn could led to potential NULL pointer accesses in subsequent calls. However, all current callers check whether they have a valid key before they call this function. So the change is primarily done for static analyzers, such as gcc -fanalyzer, to ease code analysis.
> swtpm: Return TPM_FAIL if SWTPM_NVRAM_DecrytpData is called without key

- src/swtpm/key.c
Move existing exit label before the return statement and add another label that includes the free(filebuffer). This avoids a false positive by 'gcc -fanalyzer' that seems to think that free(filebuffer) would double-free filebuffer after filebuffer = realloc(tmp, ..) failure.
> swtpm: Add another exit label to avoid gcc -fanalyzer false positive

- configure.ac
- debian/changelog
- swtpm.spec
> build-sys: Bump up version to 0.9.0 at beginning of dev cycle

- swtpm.spec
- swtpm.spec.in
The configure script requires at least gnutls-3.4.0 but this is not reflected in the spec file.
Signed-off-by: Michal Privoznik <mprivozn@redhat.com>
> swtpm.spec: Reflect minimal gnutls version

- src/swtpm/logging.c
When opening a log file fails (--log file=/some/path) for whatever reason the @logfd variable is left set to -1 (the retval of open()). And due to how _logprintf() is written, the subsequent attempt to log this failure (logprintf()) returns too early not printing the useful error.
Therefore, restore the original (CONSOLE_LOGGING) value.
Signed-off-by: Michal Privoznik <mprivozn@redhat.com>
> swtpm: Restore logging to stderr on log open failure

- man/man8/Makefile.am
- src/swtpm_setup/swtpm_setup.c
These stem mostly from what fedora's spec file is doing. Except for the swtpm_cuse man page. Handling the installation of the file properly benefits other distros as well.
> Couple of trivial fixes

- tests/Makefile.am
- tests/test_parameters
- tests/test_samples_create_tpmca
- tests/test_tpm2_parameters
- tests/test_tpm2_samples_create_tpmca.test
> tests: Fix shellcheck issue SC2115 by using "${var:?}"

- Makefile.am
- man/man8/swtpm-create-tpmca.pod
- samples/Makefile.am
- samples/swtpm-create-tpmca
- src/swtpm_localca/swtpm_localca.c
This PR fixes some issue related to the swtpm-create-tpmca tool:
- man page update
- check for availability of GnuTLS tpmtool
- Fix issues reported by shellcheck
> Sample: Fix some issues related to swtpm-create-tpmca tool

- .travis.yml
Since the tss2 package is commonly available in focal and jammy move it into to the general list of packages to installed.
libtpm2-pkcs11-tools is available since jammy, so installed it there to enable the TPM 2 pkcs11 tests.
> Travis: Update from focal to jammy and from bionic to focal

- configure.ac
`PKG_CHECK_MODULES` allows to check the library version (https://autotools.info/pkgconfig/pkg_check_modules.html - section 3.3), so there should be no need for the `AC_CHECK_LIB` call below it.
I was messing with macros in `TPMBuildSwitches.h` and would run into configure failing on https://github.com/stefanberger/swtpm/blob/459f4e7dea7320b2691dc6c69eb19a51787786fc/configure.ac#L185
libtpms was at `0.9.5` and `TPMLIB_ChooseTPMVersion` was present in `libtpms.so.*`. So that message was a little misleading.
I also found that with removing the `AC_CHECK_LIB` for `TPMLIB_ChooseTPMVersion`, the make process would tell me explicitly where an issue was. I had an undefined reference to either a variable or a function.
> Use PKG_CHECK_MODULES to check libtpms version

- tests/patches/0001-Deactivate-test-cases-accessing-rootcerts.txt.patch
- tests/patches/0002-Implement-powerup-for-swtpm.patch
- tests/patches/0003-Set-CRYPTOLIBRARY-to-openssl.patch
- tests/patches/0004-Store-and-restore-volatile-state-at-every-step.patch
- tests/patches/0005-Disable-tests-related-to-events.patch
- tests/patches/0006-Disable-testing-with-RSA-3072.patch
- tests/patches/0007-Disable-rev155-test-cases.patch
- tests/patches/0008-Disable-x509-test-cases.patch
- tests/patches/0009-Disable-getcapability-TPM_CAP_ACT.patch
- tests/patches/0010-Adjust-test-cases-for-OpenSSL-3.patch
- tests/patches/0011-Disable-ECC-encrypt-decrypt-tests.patch
- tests/patches/0012-Disable-Nuvoton-commands.patch
- tests/patches/0013-Disable-x509-test-cases-part2.patch
- tests/test_tpm2_ibmtss2
Older versions of libtpms need to have another patch applied that disables x509 certificate creation (0013-Disable-x509-test-cases-part2.patch).
> tests: ibmtss2: Add patch to disable x509 test with older libtpms

- src/swtpm_setup/swtpm_setup.c
The --version option was using the wrong goto label error rather than out to now also exit with exitcode 0.
> swtpm_setup: Exit with '0' upon --version rather than '1'.

- src/selinux/swtpm_svirt.te
The following command line did not function on an x86_64 host due to missing SELinux rules:
virt-install -v \
--name fedora-38-aarch64 \
--ram 4096 \
--disk path=fedora-38.img,cache=none \
--nographics \
--os-variant fedora38 \
--import \
--virt-type=qemu \
--arch aarch64 \
--check all=off
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2228423
With a memoryBacking node added to the libvirt domain XML, the unlink
permission on user_tmp_t:sockfile becomes necessary to avoid an avc
denial.
```
<currentMemory unit='KiB'>2097152</currentMemory>
<memoryBacking>
<hugepages>
<page size='2048' unit='KiB'/>
</hugepages>
</memoryBacking>
```
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2165142
> SELinux: Add rules for sock_file on user_tmp_t and unlink

- swtpm.spec
- swtpm.spec.in
Follow the changes in Fedora to build a separate swtpm-selinux package so that swtpm can also be installed without SELinux on the system.
> rpm: Split off SELinux files to build an selinux package

- configure.ac
Since many older gmp development packages do not provide the pkg-config file for gmp, just display a warning and fall back to default values.
> build-sys: Only display warning if pkg-config for gmp fails

- man/man8/swtpm_setup.pod
- src/swtpm_localca/swtpm_localca.c
- src/swtpm_setup/swtpm_setup.c
- src/utils/swtpm_utils.c
- src/utils/swtpm_utils.h
Test cases using swtpm_localca were failing because swtpm_localca now picked up the swtpm_cert installed in /usr/bin/swtpm_cert rather than the one in the PATH. This revert fixes the issue and users will have to adjust their PATH for out-of-PATH installations.
Resolves: https://github.com/stefanberger/swtpm/issues/829
> Revert "utils: Implement find_program() to try BINDIR path before PATH"

- include/swtpm/tpm_ioctl.h
Follow changes in the QEMU codebase supporting GNU/Hurd.
Reference: https://lists.nongnu.org/archive/html/qemu-devel/2024-01/msg03702.html
> headers: Exclude TPM ioctls definitions for the GNU/Hurd

- tests/test_swtpm_setup_misc
Some test cases can be run as root, so rearrange the order of the test cases so that not all of them are skipped if the test case runs as 'root'.
> tests: Rearrange order of test cases to run some also as 'root'

- configure.ac
- tests/Makefile.am
Add support for --disable-tests to disable the tests and the checking for tools that only need to be installed for the tests. Keep the tests enabled as default as it was before.
Resolves: https://github.com/stefanberger/swtpm/issues/843
> build-sys: Add support for --disable-tests to disable tests

- src/swtpm/cuse_tpm.c
Lock the file_ops_lock before reading the tpm_running variable so that access to access to it is serialized among all possible threads.
> swtpm: cuse: Lock file_ops_lock before reading tpm_running

- .gitignore
- CHANGES
- src/selinux/Makefile.am
- src/selinux/swtpm.te
- src/selinux/swtpm_libvirt.te
- src/selinux/swtpm_svirt.te
- swtpm.spec
- swtpm.spec.in
Due to a significant change in the targeted SELinux policy re-develop the SELinux policy for swtpm. New rules in swtpm_libvirt.te are needed when libvirt causes new interactions between types.
> selinux: Redevelop SELinux policy for Fedora 40 (ditch old rules)

- src/swtpm_setup/swtpm.c
Replace mkstemp with g_mkstemp_full and pass parameters that lead to the same mode bits and file opening flags and mkstemp had. This addresses a Coverity complaint regarding missing application of umask before mkstemp.
> swtpm: Replace mkstemp with g_mkstemp_full (Coverity)

- src/swtpm/common.c
- src/swtpm/swtpm_nvstore_dir.c
- src/swtpm/swtpm_nvstore_linear_file.c
- src/swtpm/tpmstate.c
- src/swtpm/tpmstate.h
The mode bits that the user provided were only applied with open() and were
subject to masking with the value of current umask. When umask was set to
0027 the test case test_commandline was failing because the mode bits on
the create TPM state file were not the expected ones (masked by umask).
Therefore, set the mode bits using fchmod if the user provided them,
otherwise do not set them. This way the mode bits will be set to the values
the user requested.
Currently the directory storage backend was setting the mode bits to the
default value (0640) *after* opening the TPM state file. Now, if the user
did not provide any mode bits then the mode bits will be set so that the
file can be written to as owner. This ensures that at least mode bits 0600
are set by default. However, if the user …
> swtpm: Use fchmod to set mode bits provided by user

- tests/_test_tpm2_print_states
Older versions of libtpms produced smaller initial state files. Therefore, use a regular expression to compare the sizes.
Signed-off-bby: Stefan Berger <stefanb@linux.ibm.com>
> tests: Use regex to compare --print-states sizes output

- debian/usr.bin.swtpm
Add the sys_admin capability to the profile to allow access to kernel drivers like vtpm_proxy and add write permissions for non-owner files in /var/lib/libvirt/swtpm/ to fix lock file denials
> Update apparmor profile with additional permissions

- src/selinux/swtpm_svirt.te
Reported & tested:
https://issues.redhat.com/browse/RHEL-47273
> selinux: add missing rules for libvirt system

- tests/Makefile.am
- tests/_test_swtpm_bios
- tests/_test_tpm2_file_permissions
- tests/common
- tests/installed-runner.sh
- tests/test_parameters
- tests/test_swtpm_cert
- tests/test_swtpm_setup_create_cert
- tests/test_swtpm_setup_file_backend
- tests/test_swtpm_setup_overwrite
- tests/test_tpm2_parameters
- tests/test_tpm2_swtpm_cert
- tests/test_tpm2_swtpm_cert_ecc
- tests/test_tpm2_swtpm_localca
- tests/test_tpm2_swtpm_localca_pkcs11.test
- tests/test_tpm2_swtpm_setup_create_cert
- tests/test_tpm2_swtpm_setup_overwrite
Allow tests/ to be installed and run from the system.
The installation path is loosely based on https://wiki.gnome.org/Initiatives/GnomeGoals/InstalledTests guidelines. We don't provide the .test files though, at this point. Instead, I wrote a simply installed-runner.sh script which mimics autotools basic runner. (ideally, the tests could use TAP instead etc)
Missing:
I think the current patch set should be ok for review/merge though.
> Install tests

- man/man5/swtpm_setup.conf.pod
- samples/swtpm_setup.conf.in
- src/swtpm_setup/swtpm_setup.c
- src/swtpm_setup/swtpm_setup_utils.c
- src/swtpm_setup/swtpm_setup_utils.h
This PR adds the ability to provide a default RSA keysize using swtpm_setup.conf. It is used unless the user provided it with command line option to swtpm_setup.
> Enable setting the default RSA keysize using swtpm_setup.conf

- .github/workflows/docker.yaml
- .github/workflows/release.yaml
- Dockerfile
- docker-compose.yml
Fixes #869
- Adding alpine based dockerfile
- ci: adding linter and builder github action
- ci: add testing for dockerfile
- ci: add new release action to run when published
> Adding dockerfile and ci/cd

- tests/test_tpm2_swtpm_setup_profile
Fix the following issues:
- use a regular expression instead of hard coded '4' to match StateFormatLevel number that will change in the future
- get all available profiles from running tpm rather than only the active profile -> use --info 0x40
- only compare with regular experssion if it is non-empty because this otherwise fails on Cygwin
> tests: Fix some issue with test for swtpm_setup --profile

- tests/test_tpm2_swtpm_setup_profile
A version of sed on FreeBSD requires some adjustments to the sed expressions for the test case to work. It does not support the following:
- insertion of newline using '\n' -> replace with $'...\\\n...'
- request for matching of at least one character using '\+' -> replace with '*' to match any number
> tests: Adjust sed expressions to work with BSD's sed

- tests/test_tpm2_libtpms_versions_profiles
- Use 3072bit RSA keys
- Add test case with NIST p256 key and signing
- Store modified files in git repo *after* the copy of the repo
- Suppress more tools output
> tests: Extend test case testing across libtpms versions

- man/man8/swtpm.pod
- man/man8/swtpm_cert.pod
- man/man8/swtpm_ioctl.pod
- man/man8/swtpm_localca.pod
- man/man8/swtpm_setup.pod
I noticed some spelling mistakes while reading the man pages and decided to run a spell checker on the rest
> style: found and fixed some typos in the man pages

- tests/test_tpm2_ibmtss2
The IBMTSS2 tests uite creates signatures over SHA1 that may now fail on RHEL 9.x and CentOS 9. To have these tests succeed set OPENSSL_ENABLE_SHA1_SIGNATURES=1 so the tests do not need to be modified and also check that the TPM 2 can handle SHA1 signatures as before. 'swtpm socket --tpm2' should set this environment variable automatically if needed.
> tests: Set OPENSSL_ENABLE_SHA1_SIGNATURES=1 for IBMTSS2 test

- man/man8/swtpm.pod
- src/swtpm/ctrlchannel.c
- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- src/swtpm/tpmlib.c
Use TPMLIB_WasManufactured to check whether a profile was applied since a new instance was created. If a profile was given and no new TPM 2 instance was created then display an error message and exit with an error code. This avoids silently ignoring a provided profile that was not applied since the TPM 2 instance already existed.
Make sure that a profile is only applied once by swtpm by clearing the json_profile once TPMLIB_MainInit succeeded.
> swtpm: Use TPMLIB_WasManufactured to check whether profile was applied

- src/swtpm/tpmlib.c
To avoid setting the environment variable OPENSSL_ENABLE_SHA1_SIGNATURES check whether SHA1 signature support is disabled in the TPM 2 profile. It is disabled if either 'fips-host' or the pair 'no-sha1-signing' and 'no-sha1-verification' are found among the enabled attributes.
> swtpm: Check whether SHA1 signature support is disabled in profile

- man/man8/swtpm.pod
- man/man8/swtpm_setup.pod
- src/swtpm/capabilities.c
- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
Commit 96fe5afa forgot to add cmdarg-print-profiles to the list of capabilities. Also fix typo in the man page.
Fixes: 96fe5afa ("swtpm: Add support for --print-profiles option")
> swtpm: Print cmdarg-print-profiles as part of capabilities

- .github/workflows/docker.yaml
Avoid caching of container builds to get latest libtpms version and therefore pass tests that depend on changes to libtpms.
> CI/CD: Avoid caching of container build to get latest libtpms version

- src/swtpm/check_algos.c
- tests/Makefile.am
- tests/fileinstall
- tests/sed-inplace
- tests/test_samples_create_tpmca
This PR provides some fixes to also support installed tests on BSDs where the install and sed tools work a little different than on Linux. Also fix an issue with unused function parameters that went unnoticed on Linux.
> Some fixes to run tests on BSDs

- tests/common
- tests/test_tpm2_swtpm_setup_profile
CentOS 9 and RHEL >= 9.4 (maybe earlier also) are expected to log the setting of OPENSSL_ENABLE_SHA1_SIGNATURES when a libtpms v0.9 state is used where signing a SHA1 was allowed and needs to be enable with this environment variable.
> tests: Add a check for OPENSSL_ENABLE_SHA1_SIGNATURES in log file

- src/swtpm/utils.c
- tests/test_tpm2_chroot_socket
Very old OpenSSL versions (e.g., 1.1.0i) are using /dev/urandom to get entropy while newer ones are using the getrandom syscall that does not need the device file. In some environments access to the created /dev/urandom device file may not work (EACCESS; chroot test case) and then OpenSSL will start failing operations that depend on good entropy. Therefore, check the status of the random number generator after chroot.
> swtpm: Check for good entropy source in chroot environment

- include/swtpm/tpm_ioctl.h
- src/swtpm_setup/swtpm.c
- src/swtpm_setup/swtpm.h
- src/swtpm_setup/swtpm_setup.c
Extend the list of SWTPM_INFO flags with recently added flags for
TPMLIB_GetInfo. Use the CMD_GET_INFO control channel command to get
the currently active profile for a TPM 2 from swtpm and display it in
the log every time unless it is reconfigured.
> swtpm_setup: Always log the active profile

- src/swtpm_setup/profile.c
- tests/test_tpm2_swtpm_setup_profile
Accept profiles that start their name with 'custom:' and do not exceed 32 characters. The content of these profiles will be derived from the built-in 'custom' profile unless Algorithms, Commands, or Attributes are provided on the command line.
Adjust a test case to test with profile name starting with 'custom:'.
> swtpm_setup: Accept profiles with name starting with 'custom:'

- man/man8/swtpm.pod
- man/man8/swtpm_ioctl.pod
- man/man8/swtpm_setup.pod
- src/swtpm/profile.c
- tests/Readme.md
- tests/test_tpm2_ibmtss2
- tests/test_tpm2_swtpm_setup_profile
- man: Improvements and fixes to swtpm manpage
> Misc fixes

- man/man8/swtpm.pod
- src/swtpm/capabilities.c
- src/swtpm/cuse_tpm.c
- src/swtpm/swtpm.c
- src/swtpm/swtpm_chardev.c
- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
- tests/test_tpm2_swtpm_setup_profile
Implement --print-info that takes a number as argument and uses this number as flags to call TPMLIB_GetInfo with. Dsiplay the result and exit.
Extend the man page and update other parts where swtpm_ioctl is not necessary anymore to use.
Extend a test case to also check that swtpm now returns the same result as swtpm_ioctl did before.
Append cmdarg-print-info to printed out capabilties. Adjust test cases. (Expect 'profiles' to always be part of capabilties JSON.)
> swtpm: Implement --print-info to run TPMLIB_GetInfo with flags

- tests/test_tpm2_swtpm_setup_profile
Restrict available PCR banks to sha256 & sha384 and try to enable sha256 and sha512 and check the expected results.
> tests: Test activation of PCR banks when not all are available

- include/swtpm/tpm_ioctl.h
- man/man3/swtpm_ioctls.pod
- src/swtpm/ctrlchannel.c
- src/swtpm_ioctl/tpm_ioctl.c
Introduce a structure for PTM_GET_CAPABILITY control command so that its response structure looks like the one of all the other commands. So far it has been using a plain 64 bit number. Now the upper 32bits of this number are used for the tpm_result, which is always 0, as it was up to now, and the lower 32bits are the capability flags, of which only 17 are used so far. Adjust swtpm control channel related command support code to also use the new structure.
> Introduce structure for PTM_GET_CAPABILITY

- src/swtpm/ctrlchannel.c
This reverts commit 8d4b247e3da96708a78f790c10f1d4cdbad51e79 since CMD_GET_STATEBLOB can have more than 4 bytes in response when an error happened (long-standing protocol error).
> Revert "swtpm: Print message in case error response is too long"

- tests/test_tpm2_swtpm_setup_profile
- tests/test_tpm2_swtpm_setup_profile_name
The default-v1 profile may soon also set Attributes in the JSON and therefore extend the regular expressions matching profiles to optionally match for Attributes.
> tests: Extend regex's with optional match for Attributes in profiles

- src/swtpm_setup/swtpm.c
Give two oif the (unused) fields in the tpm2_authblock better names and since these two and the continueSession fields are always initialized with '0', simplify the initializer macro to only take one argument.
> swtpm_setup: Give fields in tpm2_authblock better names

- src/swtpm/capabilities.c
- tests/_test_print_capabilities
Only display profile capabilities when --tpm2 is given since they are only relevant when a TPM 2 is used.
Adjust test cases.
> swtpm: Only display profile capabilities when --tpm2 is given

- tests/test_tpm2_ibmtss2
Check the help screen for necessary supported options since the IBM TSS2 test will have to be patched to support swtpm directly. If it does not support it, exit the tests early with an error message.
> test: Exit IBM TSS2 test early if it does not support swtpm

- configure.ac
- src/swtpm_setup/swtpm_backend_dir.c
My local filesystem is btrfs with a long life. It's inodes ecxeed 32-bit
space and that causes test failures in `swtpm` on `i686-linux`
containers:
FAIL: test_parameters
FAIL: test_swtpm_setup_file_backend
FAIL: test_swtpm_setup_overwrite
FAIL: test_tpm2_swtpm_setup_create_cert
FAIL: test_tpm2_swtpm_setup_overwrite
FAIL: test_swtpm_setup_create_cert
FAIL: test_tpm2_parameters
The example test failure log looks this way:
FAIL: test_migration_key
========================
Need to be root to run test with CUSE interface.
Need to be root to run test with CUSE interface.
==== Starting swtpm with interfaces socket+socket ====
Test 1: Ok
==== Starting swtpm with interfaces socket+socket ====
Test 2: Ok
==== Starting swtpm with interfaces socket+socket ====
swtpm: Missing migration key to decrypt …
> configure.ac: enable 64-bit file API on 32-bit systems

- src/swtpm/check_algos.c
Move the 'Tested: tdes' type of debugging output one more indentation level up so that they can be filtered-out easier from control and data channel communication.
> swtpm: Indent 'Tested' output of tested algorithm by one more space

- debian/usr.bin.swtpm
QEMU's functional tests need access to /var/tmp/**. To avoid the following
type of AppArmor permission failures add a rule that allows access to
/var/tmp/**.
type=AVC msg=audit(1730829888.863:260): apparmor="DENIED" \
operation="mknod" class="file" profile="swtpm" \
name="/var/tmp/qemu_3r9txw7z/swtpm-socket" pid=3925 comm="swtpm" \
requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000FSUID="stefanb" \
OUID="stefanb"
[ To run the QEMU's functional tests use the following command:
make check-functional ]
> debian: Add rule to allow usage of /var/tmp directory (QEMU)

- src/swtpm/utils.c
- src/swtpm_setup/profile.c
- src/utils/swtpm_utils.c
If '{"Name":null}' is provided to the parser, the 'null' will not cause a parser exception but return a NULL pointer when trying to get the value of "Name". In some cases the callers assume that a NULL pointer is never returned. Handle those cases where the NULL pointer would cause segmentation faults, particularly when the user provides the input (swtpm_setup patch).
> Handle cases where json_reader_get_string_value returns NULL pointer

- .travis.yml
There seems to be a well known error in setuptools 71.x that prevents installation of cpp-coveralls on Travis now:
File "/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
canonicalize_version(version, strip_trailing_zero=False),
TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
Fall back to the default version that is used in Ubuntu Jammy (59.6.0) since later versions also lead to the same error.
Link: https://github.com/pypa/setuptools/issues/4483
> Travis: Downgrade to setuptools 59.6.0 to avoid error in 71.x

- man/man8/swtpm_setup.pod
- src/swtpm_setup/swtpm_setup.c
Improve the swtpm_setup --tpm option documentation that did not mention that the socket option must be passed along when swtpm is being used.
> man: Improve swtpm_setup --tpm option documentation

- src/swtpm_setup/profile.c
Make sure there is a '/' after DATAROOTDIR.
> swtpm-setup: fix invalid profile distro path

- src/selinux/swtpm.te
Some extra permissions for mmap & nfs states.  Fixes #970
> Missing SELinux permissions

- src/swtpm_setup/swtpm_setup.c
- tests/test_tpm2_swtpm_setup_create_cert
Ensure that no profile is passed to the TPM 2 when it is to be reconfigured by:
- Showing an error if user tries to pass a profile when also --reconfigure is passed
- Not taking the default profile from the swtpm_setup.conf configuration file if the user did not pass a profile
Extend an existing test case with a default profile in its swtpm_setup.conf so that the above 2nd item is tested.
> swtpm_setup: Do not pass a TPM 2 profile to swtpm when reconfiguring

- man/man8/swtpm-create-tpmca.pod
- samples/swtpm-create-tpmca
- tests/test_tpm2_samples_create_tpmca.test
Extend swtpm-create-tpm to support rsa2048 (default), rsa3072, ecc256 (NIST P256), and ecc384 (NIST P384) for the created TPM 2 CA. The names are taken from the output of:
tpm2_ptool addkey --help
ecc521 does not seem to work with the TPM 2 stack even though it is advertised as a possible option.
Extend an existing test case to create an ecc256 key and extend man page.
> samples: Support different key algorithms for created TPM 2 CA

- samples/swtpm-create-tpmca
- tests/test_tpm2_samples_create_tpmca.test
Enable passing the usual curve names of secp256r1 and secp384r1 instead of ecc256 and ecc384 on the command line of swtpm-create-tpmca.
> sample: Enable passing usual curve names secp256r1 or secp384r1

- src/swtpm/profile.c
- src/swtpm/utils.c
- src/swtpm/utils.h
Use the custom profile's Algorithms when adjusting them for FIPS mode, rather than the list of all implemented Algorithms. The list of implemented Algorithms contains for example elliptic curve identifiers, such as ecc-nist-p192, ecc-nist-p224, ecc-nist-p256, ecc-nist-p384, ecc-nist-p521, ecc-bn-p256, ecc-bn-p638, that are not part of the custom profile but are enabled with the ecc-min-size=192, ecc-nist, and ecc-bn shortcuts there. Using the algorithms of the custom profile avoids confusion since otherwise the additional ecc-nist-* and ecc-bn-* algorithm identifiers appear in the modified custom profile even though the were not part of the original one.
Test:
swtpm_setup --tpm2 --tpmstate . --overwrite \
--profile-name custom --profile-remove-disabled fips-host
before: …
> swtpm: Use custom profile's Algorithms when removing FIPS-disabled ones

- src/swtpm/mainloop.c
Coverity complains that the assignment of connection_fd.fd = mlp->fd leaks the value of connection_fd.fd. However, the logic is so that this cannot happen because further down in the loop:
1) only when connection_fd.fd < 0, then pollfds[DATA_SERVER_FD] gets
a value
2) connection_fd.fd = accept() only happens if 1) happened
However, if mlp->flags & MAIN_LOOP_FLAG_USE_FD is != 0 then connection_fd was assigned a value and 1) never happens.
=> Fix the Coverity complaint even though it is a false positive.
> swtpm: Close connection_fd.fd before assigning new value (CID 459830)

- swtpm.spec
•  Uninstall ‘swptm_svirt’ selinux module first before uninstalling the ‘swtpm’ module.
•  Add the %selinux_relabel_pre macro to back up the original file contexts lists.
Signed-off-by: Ajeeth Adithya <ajeeth.adithya@nutanix.com>
> Fix SELinux related bugs in the swtpm.spec file

- .github/workflows/ci.yml
Github actions does not run ubuntu-20.04 anymore ue to EOL. Update the entries.
> ci: Update from ubuntu-20.04 to ubuntu-22.04 due to EOL

- .github/workflows/ci.yml
Github actions does not run ubuntu-20.04 anymore due to EOL. Update the 20.04 entries to use 24.04.
cpp-coveralls needs an older version of python3 due to pkgutil.ImpImporter having disappeared in more recent python versions. Therefore, leave test-coveralls at 22.04.
> ci: Update from ubuntu-20.04 to ubuntu-24.04 due to EOL

- src/swtpm/swtpm_nvstore_dir.c
- src/swtpm/utils.c
- src/swtpm/utils.h
Remove the unused fsync code from the directory backend. It could cause TPM command timeouts if used.
Factor-out file reading and writing code.
> Cleanup and factor-out file reading and writing in directory backend

- src/swtpm/utils.c
Define ACCESSPERMS if it is not defined, such as for example on Alpine.
> swtpm: Define ACCESSPERMS if not defined in sys/stat.h

- include/swtpm/tpm_ioctl.h
- src/swtpm/swtpm_nvstore_linear_file.c
- src/swtpm_setup/swtpm_backend_dir.c
- tests/common
- tests/sed-inplace
The build of swtpm currently fails on GNU/Hurd systems due to some issues related to header files. Fix them.
However, the test cases require either netstat or ss tools, of which neither seems to be available. Therefore, `--disable-tests` needs to be passed to configure script. Also socat 1.7.x seems broken and cannot run the unix command socket tests.
> Fix some issues preventing the build on GNU/Hurd systems from succeeding

- debian/rules
The build for RISC-V causes timeouts when running tests in parallel due to the CPU being emulated. Avoid the timeouts by not running parallel tests.
> debian: Do not user parallel testing to avoid timeouts

- tests/patches/0011-Remove-unnecessary-include-of-openssl-engine.h.patch
- tests/test_tpm2_ibmtss2
To keep the older version of the IBM TSS2 test suite working, remove the unnecessary include of openssl/engine.h to allow it to compile with more recent versions of OpenSSL where this header file is missing.
> tests: Remove unnecessary include of openssl/engine.h

- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
libtpms v0.11 will support RSA-4096 keys. Adjust the test case regex for optional output of 'tpm2-rsa-keysize-4096'.
> tests: Extend regex to allow for optional RSA-4096 keys

- configure.ac
- swtpm.spec
- tests/_test_print_capabilities
- tests/_test_tpm2_print_capabilities
Libtpms v0.11 supports RSA-4096 bit keys and therefore we have to adjust the test cases to allow for optional advertisement of these keys through `tpm2-rsa-keysize-4096`. Also, there's currently nothing in (future) libtpms v0.11 that would not allow us to use it with swtpm v0.10.x.
> Enable building with libtpms v0.11

- src/swtpm/ctrlchannel.c
Return an error code if HASH_DATA received more bytes from the user than what the user indicated in the length field that he wanted to send. This avoids an integer underrun of the 'remain' variable in the loop that would then cause the loop to wanting to receive around 4GB of data.
Also fix some indentation issues.
Use be32toh instead of (the equivalent) htobe32 when reading from the packet.
> swtpm: Return error if more bytes received than user wanted to send

- configure.ac
- src/swtpm/cuse_tpm.c
libfuse2 contains unaddressed security issue. (libfuse/libfuse#15)
this patch adds a configuration flag `--with-fuse3`, when it is explicitly set, swtpm would be built against libfuse3 instead of libfuse2.
while `--with-fuse3` is not set, the package is built against libfuse2 as conventional, this avoid breaking existing build systems from various distros.
- configure.ac: add flag `--with-fuse3`, which requires enabling explicitly
- src/swtpm/cuse_tpm.c: add libfuse3 support, mainly MARCOs and `fuse_session_loop_mt()` reimplementation
with successful building and testing (returns 0) with both 2 configurations below, it seems the patched source is working?
```
autoreconf --install --force
./configure --with-cuse  # fuse2
make clean && make && make check
```
```
autoreconf --install --force …
```
> cuse: add support to libfuse3 while avoid introducing breaking change

- configure.ac
This cleans up configure.ac, the hard coding of the pkgconf is causing cross compile problems. The non-m4sh can cause problems with pkgconf macros though. These patches fix that up.
> configure.ac: Use pkgconf macros, use m4sh, remove obsolete sections

- tests/test_tpm2_parameters
- tests/test_tpm2_swtpm_setup_create_cert
- tests/test_tpm2_swtpm_setup_profile
- tests/test_tpm2_swtpm_setup_profile_name
RSA-4096 is enabled in libtpms v0.11 and requires that default-v2 profile be used. Extend existing test case with test for RSA-4096 and default-v2 profile.
> tests: Extend test cases with RSA-4096 and default-v2 testing
